//
// Copyright (c) Microsoft Corporation.  All rights reserved.
//
//
// Use of this source code is subject to the terms of the Microsoft shared
// source or premium shared source license agreement under which you licensed
// this source code. If you did not accept the terms of the license agreement,
// you are not authorized to use this source code. For the terms of the license,
// please see the license agreement between you and Microsoft or, if applicable,
// see the SOURCE.RTF on your install media or the root of your tools installation.
// THE SOURCE CODE IS PROVIDED "AS IS", WITH NO WARRANTIES OR INDEMNITIES.
//
//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by common.rc
//
#define IDS_IFD_WARN_MISSING_TEST_RESULT 801
#define IDS_IFD_WARN_MISSING_TEST_START 802
#define IDS_IFD_FAILED_STRING           803
#define IDS_IFD_PASSED                  804
#define IDS_IFD_IOCTL_FAILED            805
#define IDS_IFD_IOCTL_WRONG_NUMBYTES    806
#define IDS_IFD_WRONG_STATUS            807
#define IDS_IFD_IOCTL_BAD_DATA          808
#define IDS_IFD_NULL_STRING             809
#define IDS_IFD_NOT                     810
#define IDS_IFD_CHECK_TEST_SUCCESS_MSG  811
#define IDS_IFD_CHECK_NOT_SUPPORTED_MSG 812
#define IDS_CARD_TESTED_ALREADY         813
#define IDS_TESTING_CARD                814
#define IDS_TEST_NO                     815
#define IDS_CARD_UNKNOWN                816
#define IDS_CURRENT_CARD                817
#define IDS_REMOVE_CARD                 818
#define IDS_PART_A                      819
#define IDS_READER_FAILED               820
#define IDS_SMART_CARD_PRESENT          821
#define IDS_SEVICE_CONTROL_IO_SHOULD_RET_TRUE 822
#define IDS_READER_FAILED_CARD_REM      823
#define IDS_SMART_CARD_ABSENT           824
#define IDS_DEV_IO_CTRL_SHOULD_RET_TRUE_CARD_REM 825
#define IDS_INS_REM_SMART_CARD          826
#define IDS_READER_FAILED_WITH_RET_VAL  827
#define IDS_READER_FAILED_CARD_REM_WITH_RET_VAL 828
#define IDS_PRESS_ANY_KEY               829
#define IDS_PART_B                      830
#define IDS_DEV_NAME                    831
#define IDS_DEV_NAME_NOT_NT4_COMPLIANT  832
#define IDS_DEV_NAME_NOT_WDM_PNP_COMPLIANT 833
#define IDS_NULL_PTR_CHK                834
#define IDS_IOCTRL_SMARTCARD_GET_ATTRIBUTE_SHOULD_RET 835
#define IDS_CLOSE_DRIVER_WITH_IO_REQ_PENDING 836
#define IDS_WAIT_FOR_PRESENT_SUCCEED_UNEXPECTED 837
#define IDS_READER_FAILED_TO_TERMINATE_PENDING_IO_REQ 838
#define IDS_PLS_INS_SAMPLE_PC_SC_COMPLIANCE_CARD 839
#define IDS_READER_TEST_SKIPPED         840
#define IDS_RES_MGR_SIMULATION_SKIPPED  841
#define IDS_SMART_CARD_PROVIDER_TEST_SKIPPED 842
#define IDS_SMART_CARD_PROVIDER_TEST    843
#define IDS_PART_D                      843
#define IDS_INS_ANY_PC_SC_COMPLIANCE_CARD 844
#define IDS_UNABLE_TO_RESET_SMART_CARD  845
#define IDS_POWER_MGMT_TEST_SKIPPED     846
#define IDS_READER_FAILED_TEST          847
#define IDS_READER_PASSED_TEST          848
#define IDS_CARD_MONITOR_TEST_SKIPPED   849
#define IDS_COLD_RESET                  850
#define IDS_COLD_RESET_FAILED           851
#define IDS_COLD_RESET_TOOK_TIME        852
#define IDS_SET_PROTOCOL_T0_T1          853
#define IDS_SET_PROTOCOL_FAILED         854
#define IDS_IOCTL_SCARD_ATT_VENDOR_NAME_FAILED 855
#define IDS_NO_VENDOR_NAME_DEFINED      856
#define IDS_SCARD_ATTR_VENDOR_IFD_TYPE_FAILED 857
#define IDS_NO_IFD_TYPE_DEFINED         858
#define IDS_SCARD_ATTR_DEVICE_UNIT_FAILED 859
#define IDS_SCARD_ATTR_ATR_STRING_FAILED 860
#define IDS_READER_RET_ATR_WITH_NO_CARD_INS 861
#define IDS_SCARD_ATTR_DEFAULT_CLK_SCARD_ATTR_MAX_CLK_FAILED 862
#define IDS_SCARD_ATTR_DEFAULT_DATA_RATE_SCARD_ATTR_MAX_DATA_RATE_FAILED 863
#define IDS_SCARD_ATTR_MAX_IFSD_FAILED  864
#define IDS_SCARD_ATTR_PROTOCOL_TYPES_FAILED 865
#define IDS_READER_MUST_SUPPORT_T_0_AND_1 866
#define IDS_SCARD_ATTR_CURRENT_PROTOCOL_TYPE_FAILED 867
#define IDS_READER_RETURNED_NO_PROTOCOL 868
#define SCARD_ATTR_CURRENT_PROTOCOL_TYPE_FAILED 869
#define IDS_IOCTL_RET                   870
#define IDS_PLS_INS_SMART_CARD          871
#define IDS_IOCTL_SMARTCARD_GET_STATE   872
#define IDS_IOCTL_SMARTCARD_GET_STATE_FAILED 873
#define IDS_INVALID_READER_STATE        874
#define IDS_COLD_RESET_FAILED_WITH_RET_VAL 875
#define IDS_INVALID_VAL_0_3             876
#define IDS_INVALID_VAL_1000_20000      877
#define IDS_INVALID_VAL_1_254           878
#define IDS_PART_C                      879
#define IDS_CARD_INS_FAILED_RET_VAL     880
#define IDS_GET_OVERLAPPED_RESULT       881
#define IDS_SMART_CARD_NOT_REMOVED      882
#define IDS_CARD_REM_FAILED_RET_VAL     883
#define IDS_CHECKING_READER_STATUS      884
#define IDS_READER_RET_ILLEGAL_STATE    885
#define IDS_INVALID_READER_STATE_CUR_EXPECTED_STATE 886
#define IDS_IOCTL_SMART_CARD_PRESENT    887
#define IDS_MON_SUPPOSE_TO_RET          888
#define IDS_IOCTL_SMARTCARD_IS_ABSENT_FAILED_RET_VAL 889
#define IDS_COLD_RESET_CARD             890
#define IDS_COLDRESET                   891
#define IDS_PROTOCOL_SEL_FAILED_WITH_ERROR 892
#define IDS_SCARD_POWER_DOWN            893
#define IDS_IOCTL_SMARTCARD_POWER_FAILED 894
#define IDS_READER_RET_INVALID_STATE    895
#define IDS_PART_E                      896
#define IDS_NOTE                        897
#define IDS_INSTRUCTION                 898
#define IDS_ENABLE_SHUTDOWN_PRIVILEGE   899
#define IDS_TEST1                       900
#define IDS_HIBERNATING_NOW             901
#define IDS_HIBERNATE_FAILED            902
#define IDS_GET_OVERLAPPED_RESULT_FAILED 903
#define IDS_INSERT_CARD                 904
#define IDS_CHK_READER_STATUS           905
#define IDS_READER_FAILED_IOCTL_SMARTCARD_GET_STATE 906
#define IDS_INVALID_READER_RET_EXPECTED 907
#define IDS_TEST2                       908
#define IDS_CARD_IN_OUT                 909
#define IDS_TEST_NO_INS_CARD            910
#define IDS_REM_SMART_CARD              911
#define IDS_TEST_NO_REM_CARD            912
#define IDS_TEST3                       913
#define IDS_CARD_IN_IN                  914
#define IDS_TEST4                       915
#define IDS_CARD_OUT_IN                 916
#define IDS_ENABLE_SHUTDOWN_PRIVILEGE_FAILED 917
#define IDS_VENDOR_IFDTYPE              918
#define IDS_SELECT_READER               919
#define IDS_LOOK_UP_PRIVILEGE_VAL_FAILED 920
#define IDS_OPEN_PROCESS_TOKEN_FAILED   921
#define IDS_OPEN_THREAD_TOKEN_FAILED    922
#define IDS_SMART_CARD_READER_TEST      923
#define IDS_VERSION                     924
#define IDS_COPY_RIGHT                  925
#define IDS_VALID_CMD_LINE_PARAMETERS   926
#define IDS_INVALID_PARAMETER           927
#define IDS_USAGE                       928
#define IDS_USAGE_DUMPS_ALL             929
#define IDS_USAGE_ENDS_SERVICE          930
#define IDS_USAGE_AUTOIFD               930
#define IDS_USAGE_MANUAL_TEST           931
#define IDS_USAGE_READER_USING_DEV_NAME 932
#define IDS_USAGE_SKIP_CARD_MONITOR_TEST 933
#define IDS_USAGE_N                     933
#define IDS_USAGE_SKIP_GENERAL_READER_TEST 934
#define IDS_USAGE_X                     934
#define IDS_TEST_CHECK_INVALID_HANDLE   934
#define IDS_USAGE_SKIP_RESOURCE_MANAGER_TEST 935
#define IDS_USAGE_Y                     935
#define IDS_HANDLE_UNEXPECTEDLY_VALID   935
#define IDS_USAGE_SKIPS_CARDS_TEST      936
#define IDS_USAGE_SKIP_POWER_MGMT_TEST  937
#define IDS_USAGE_READER_USING_VENDOR_NAME 938
#define IDS_USAGE_SPECIFIC_TEST         939
#define IDS_USAGE_WAITING_TIME          940
#define IDS_NO_READER_FOUND             941
#define IDS_CAN_NOT_OPEN_SMART_CARD_READER 942
#define IDS_VENDOR                      943
#define IDS_READER                      944
#define IDS_DATE                        945
#define IDS_TIME                        946
#define IDS_OS                          947
#define IDS_VENDORNAME                  948
#define IDS_IFDTYPE                     949
#define IDS_DEVICE_CLASSES_KEY          950
#define IDS_SYMB_LINK                   951
#define IDS_SCREADER                    952
#define IDS_DEV_KEY                     953
#define IDS_DEBUG_IFDTYPE               954
#define IDS_DEBUG_VENDOR                955
#define IDS_REQ_DATA                    956
#define IDS_IOCTL_RET_VAL               957
#define IDS_REPLY_DATA                  958
#define IDS_SCRIPT_FILE_CAN_NOT_OPENED  959
#define IDS_MISSING_AND_IN_FUN          960
#define IDS_MISSING_CMD_APDU            961
#define IDS_LINE_INVALID                962
#define IDS_ILLEGAL_VAL_FOUND           963
#define IDS_CARD_CMD_FOUND_NO_CARD_DEFINED 964
#define IDS_IFDTEST_DAT_FILE            965
#define IDS_MANUAL_READER_TEST          966
#define IDS_CMDS                        967
#define IDS_OTHER_CMDS                  968
#define IDS_READER_CMDS                 969
#define IDS_CARD_CMDS                   970
#define IDS_OTHER_EXIT_CMD              971
#define IDS_INFO                        972
#define IDS_REPEAT_CNT                  973
#define IDS_ENT_CMD                     974
#define IDS_INVALID_SEL                 975
#define IDS_CHANGING_T_0                976
#define IDS_CHANGING_T_1                977
#define IDS_WARM_RESET                  978
#define IDS_POWERDOWN                   979
#define IDS_HIBERNATING_TEST_1_MIN      980
#define IDS_CARD_INSERTED               981
#define IDS_CARD_REMOVED                982
#define IDS_INS_CARD                    983
#define IDS_GET_STATE                   984
#define IDS_GET_STATE_1                 985
#define IDS_WAITING_FOR_REMOVAL         986
#define IDS_WAITING_FOR_INSERTION       987
#define IDS_UNKNOWN_STATE               988
#define IDS_TEST_VENDOR_IOCTL           989
#define IDS_RET_VAL                     990
#define IDS_DATA_RET                    991
#define IDS_ABSENT_STATE                992
#define IDS_PRESENT_STATE               993
#define IDS_SWALLOWED_STATE             994
#define IDS_POWERED_STATE               995
#define IDS_NEGOTIABLE_STATE            996
#define IDS_SPECIFIC_STATE              997
#define IDS_STRING998                   998
#define IDS_SC_READER                   998
#define IDS_REM_ALL_CARDS               999
#define IDS_SC_WINCE_READER             1000
#define IDS_DEV_NAME_NOT_WINCE_COMPLIANT 1001
#define IDS_WAIT_FOR_ABSENT_SUCCEED_UNEXPECTED 1002
#define IDS_CANCELIO_RETURN_ERROR       1003
#define IDS_OPEN_DRIVER                 1004
#define IDS_CANNOT_OPEN_DRIVER          1005
#define IDS_SUSPEND_AND_WAKEUP_RETURN_ERROR 1006
#define IDS_WAIT_FOR_REMOVE_FAILED      1007
#define IDS_CANNOT_CLOSE_THREAD_HANDLE  1008
#define IDS_CANNOT_CREATE_SUSPEND_WAKEUP_THREAD 1009
#define IDS_WAIT_FOR_INSERT_FAILED      1010
#define IDS_CANCEL_BLOCKING_DEVICEIOCONTROL_CALL 1011
#define IDS_COULD_NOT_ALLOCATE_POWER_UTILITY 1012
#define IDS_COULD_NOT_SETUP_RTC         1013
#define IDS_POLLING_ON_STATE_FAILED     1014
#define IDS_SYSTEM_HAS_RESUMED          1015
#define IDS_GET_SYSTEMPOWERSTATE_FAILED 1016
#define IDS_TESTNUM_TESTNAME            1017
#define IDS_PROGRAM_NAME                1018
#define IDS_SYSTEM_GOING_TO_SLEEP_NOW   1019
#define IDS_TEST_INSERTREMOVE           1020
#define IDS_TEST_REMOVEREADERS          1021
#define IDS_TEST_INSERTREADER           1022
#define IDS_TEST_START_ITERATIONNUM     1023
#define IDS_TEST_CLOSEREADER            1024
#define IDS_CAN_NOT_CLOSE_SMART_CARD_READER 1025
#define IDS_STRING1026                  1026
#define IDS_TEST_OPENREADER             1026
#define IDS_READER_STILL_FOUND          1027
#define IDS_CANNOT_CREATE_SWITCHBOX_THREAD 1028
#define IDS_SWITCHBOX_THREAD_FAILED     1029
#define IDS_TEST_INTERRUPTREADER        1030
#define IDS_USAGE_USBSWITCHBOX          1031
#define IDS_TEST_READERREMOVALWHENBLOCKED 1031
#define IDS_USAGE_N2                    1032
#define IDS_USAGE_P                     1032
#define IDS_USAGE_C                     1033
#define IDS_CANNOT_INITIALIZE_SWITCHBOX 1034
#define IDS_TEST_REMOVEREADER_DURING_TEST 1035
#define IDS_READER_INTERRUPT_TIME       1036
#define IDS_USAGE_S                     1037
#define IDS_AUTOIFD_PASS_UNEXPECTED     1037
#define IDS_TEST_RESUMETHREAD           1038
#define IDS_COULD_NOT_RESUMETHREAD      1039
#define IDS_CLOSE_DRIVER                1040
#define IDS_COULD_NOT_ALLOCATE_TEST_STRUCTURES 1041
#define IDS_TEST_MULTIPLEDEVICE         1042
#define IDS_TEST_MULTIREADER_AUTOIFD    1042
#define IDS_TEST_SIMULTANEOUSREADERS    1043
#define IDS_DETECTEDCARD_ITER           1043
#define IDS_DETECTEDCARD_INSREM_TER     1043
#define IDS_DETECTEDCARD_INSREM_ITER    1043
#define IDS_TEST_SUSPENDRESUME_INSERTREMOVE 1044
#define IDS_TEST_SUSPENDRESUME_INSERTREMOVE_NOTE 1045
#define IDS_REMOVEINSERT_DURING_SUSPEND 1046
#define IDS_REMOVEINSERT_DIFFERENTPORT_DURING_SUSPEND 1047
#define IDS_REMOVE_NOINSERT_DURINGSUSPEND_SAMEPORT 1048
#define IDS_REMOVE_NOINSERT_DURINGSUSPEND_DIFFPORT 1049
#define IDS_INSERT_DURING_SUSPEND       1050
#define IDS_STRESS_FAILURE_COUNT        1051

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        103
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
