!if 0
Copyright (c) Microsoft Corporation.  All rights reserved.
!endif
!if 0
Use of this source code is subject to the terms of the Microsoft
premium shared source license agreement under which you licensed
this source code. If you did not accept the terms of the license
agreement, you are not authorized to use this source code.
For the terms of the license, please see the license agreement
signed by you and Microsoft.
THE SOURCE CODE IS PROVIDED "AS IS", WITH NO WARRANTIES OR INDEMNITIES.
!endif


#Projects that use unfiltered headers and presysgen libraries must have a makefile in $(_PUBLICROOT)\$(WINCETREE)\cesysgen\ ( enforced my makefile.def )
WINCEPROJ=test
!INCLUDE $(_PUBLICROOT)\common\cesysgen\cesysgen.mak


#Copy logic for winceos\testtools now located in $(_PRIVATEROOT)\test\common\external\makefile.inc, build there before the rest of test.
preproc:
postproc: 
