//
// Copyright (c) Microsoft Corporation.  All rights reserved.
//
//
// Use of this source code is subject to the terms of your Microsoft Windows CE
// Source Alliance Program license form.  If you did not accept the terms of
// such a license, you are not authorized to use this source code.
//
#include "TUXMAIN.H"
#include "ERRORMAP.H"

BEGINMAP(MMRESULT,lpErrorMap)
ENTRY(WAVERR_BADFORMAT)
ENTRY(MMSYSERR_ERROR)
ENTRY(MMSYSERR_BADDEVICEID)
ENTRY(MMSYSERR_NOTENABLED)
ENTRY(MMSYSERR_ALLOCATED)
ENTRY(MMSYSERR_INVALHANDLE)
ENTRY(MMSYSERR_NODRIVER)
ENTRY(MMSYSERR_NOMEM)
ENTRY(MMSYSERR_NOTSUPPORTED)
ENTRY(MMSYSERR_BADERRNUM)
ENTRY(MMSYSERR_INVALFLAG)
ENTRY(MMSYSERR_INVALPARAM)
ENTRY(MMSYSERR_HANDLEBUSY)
ENTRY(MMSYSERR_INVALIDALIAS)
ENTRY(MMSYSERR_BADDB)
ENTRY(MMSYSERR_KEYNOTFOUND)
ENTRY(MMSYSERR_READERROR)
ENTRY(MMSYSERR_WRITEERROR)
ENTRY(MMSYSERR_DELETEERROR)
ENTRY(MMSYSERR_VALNOTFOUND)
ENTRY(MMSYSERR_NODRIVERCB)
ENTRY(MMSYSERR_LASTERROR)
ENDMAP

Map<MMRESULT> g_ErrorMap(lpErrorMap,MAPSIZE(lpErrorMap));

