//
// Copyright (c) Microsoft Corporation.  All rights reserved.
//
//
// Use of this source code is subject to the terms of the Microsoft shared
// source or premium shared source license agreement under which you licensed
// this source code. If you did not accept the terms of the license agreement,
// you are not authorized to use this source code. For the terms of the license,
// please see the license agreement between you and Microsoft or, if applicable,
// see the SOURCE.RTF on your install media or the root of your tools installation.
// THE SOURCE CODE IS PROVIDED "AS IS", WITH NO WARRANTIES OR INDEMNITIES.
//
////////////////////////////////////////////////////////////////////////////////
//
//  TUXTEST TUX DLL
//  Copyright (c) Microsoft Corporation
//
//  Module: 411_JPN.h
//          
//
//  Revision History:changed #define values:
//
////////////////////////////////////////////////////////////////////////////////

UINT8 JPN_411_ScToVk[] = {
    /* 01 */  VK_F9,
    /* 02 */  0,
    /* 03 */  VK_F5,
    /* 04 */  VK_F3,
    /* 05 */  VK_F1,
    /* 06 */  VK_F2,
    /* 07 */  VK_F12,
    /* 08 */  0,
    /* 09 */  VK_F10,
    /* 0A */  VK_F8,
    /* 0B */  VK_F6,
    /* 0C */  VK_F4,
    /* 0D */  VK_TAB,
    /* 0E */  VK_DBE_SBCSCHAR,
    /* 0F */  0,
    /* 10 */  0,
    /* 11 */  VK_LMENU,
    /* 12 */  VK_LSHIFT,
    /* 13 */  VK_DBE_HIRAGANA,
    /* 14 */  VK_LCONTROL,
    /* 15 */  'Q',
    /* 16 */  '1',
    /* 17 */  0,
    /* 18 */  0,
    /* 19 */  0,
    /* 1A */  'Z',
    /* 1B */  'S',
    /* 1C */  'A',
    /* 1D */  'W',
    /* 1E */  '2',
    /* 1F */  0,
    /* 20 */  0,
    /* 21 */  'C',
    /* 22 */  'X',
    /* 23 */  'D',
    /* 24 */  'E',
    /* 25 */  '4',
    /* 26 */  '3',
    /* 27 */  0,
    /* 28 */  0,
    /* 29 */  VK_SPACE,
    /* 2A */  'V',
    /* 2B */  'F',
    /* 2C */  'T',
    /* 2D */  'R',
    /* 2E */  '5',
    /* 2F */  0,
    /* 30 */  0,
    /* 31 */  'N',
    /* 32 */  'B',
    /* 33 */  'H',
    /* 34 */  'G',
    /* 35 */  'Y',
    /* 36 */  '6',
    /* 37 */  0,
    /* 38 */  0,
    /* 39 */  0,
    /* 3A */  'M',
    /* 3B */  'J',
    /* 3C */  'U',
    /* 3D */  '7',
    /* 3E */  '8',
    /* 3F */  0,
    /* 40 */  0,
    /* 41 */  VK_COMMA,
    /* 42 */  'K',
    /* 43 */  'I',
    /* 44 */  'O',
    /* 45 */  '0',
    /* 46 */  '9',
    /* 47 */  0,
    /* 48 */  0,
    /* 49 */  VK_PERIOD,
    /* 4A */  VK_SLASH,
    /* 4B */  'L',
    /* 4C */  VK_SEMICOLON,
    /* 4D */  'P',
    /* 4E */  VK_HYPHEN,
    /* 4F */  0,
    /* 50 */  0,
    /* 51 */  0xE2,
    /* 52 */  VK_APOSTROPHE,
    /* 53 */  0,
    /* 54 */  VK_BACKQUOTE,
    /* 55 */  VK_EQUAL,
    /* 56 */  0,
    /* 57 */  0,
    /* 58 */  VK_DBE_ALPHANUMERIC,
    /* 59 */  VK_RSHIFT,
    /* 5A */  VK_RETURN,
    /* 5B */  VK_LBRACKET,
    /* 5C */  0,
    /* 5D */  VK_RBRACKET,
    /* 5E */  0,
    /* 5F */  0,
    /* 60 */  0,
    /* 61 */  0,
    /* 62 */  0,
    /* 63 */  0,
    /* 64 */  VK_CONVERT,
    /* 65 */  0,
    /* 66 */  VK_BACK,
    /* 67 */  VK_NOCONVERT,
    /* 68 */  0,
    /* 69 */  VK_NUMPAD1,
    /* 6A */  VK_BACKSLASH,
    /* 6B */  VK_NUMPAD4,
    /* 6C */  VK_NUMPAD7,
    /* 6D */  0,
    /* 6E */  0,
    /* 6F */  0,
    /* 70 */  VK_NUMPAD0,
    /* 71 */  VK_DECIMAL,
    /* 72 */  VK_NUMPAD2,
    /* 73 */  VK_NUMPAD5,
    /* 74 */  VK_NUMPAD6,
    /* 75 */  VK_NUMPAD8,
    /* 76 */  VK_ESCAPE,
    /* 77 */  VK_NUMLOCK,
    /* 78 */  VK_F11,
    /* 79 */  VK_ADD,
    /* 7A */  VK_NUMPAD3,
    /* 7B */  VK_SUBTRACT,
    /* 7C */  VK_MULTIPLY,
    /* 7D */  VK_NUMPAD9,
    /* 7E */  VK_SCROLL,
    /* 7F */  0,
    /* 80 */  0,
    /* 81 */  0,
    /* 82 */  0,
    /* 83 */  VK_F7,
    /* 84 */  VK_SNAPSHOT,
    /* 85 */  0,
    /* 86 */  0,
    /* 87 */  0,
    /* 88 */  0,
    /* 89 */  0,
    /* 8A */  0,
    /* 8B */  0,
    /* 8C */  0,
    /* 8D */  0,
    /* 8E */  0,
    /* 8F */  0,
};
