//
// Copyright (c) Microsoft Corporation.  All rights reserved.
//
//
// Use of this source code is subject to the terms of the Microsoft shared
// source or premium shared source license agreement under which you licensed
// this source code. If you did not accept the terms of the license agreement,
// you are not authorized to use this source code. For the terms of the license,
// please see the license agreement between you and Microsoft or, if applicable,
// see the SOURCE.RTF on your install media or the root of your tools installation.
// THE SOURCE CODE IS PROVIDED "AS IS", WITH NO WARRANTIES OR INDEMNITIES.
//
//#include <resbases.h>
#define RESBASE     0

// Used by cmdrsc.rc
//
#define IDS_ABORT_MEMORY                (RESBASE+1)
#define IDS_HELP_CMD_EXIT               (RESBASE+2)
#define IDS_HELP_CMD_HELP               (RESBASE+3)
#define IDS_HELP_CMD_SET                (RESBASE+4)
#define IDS_HELP_CMD_ECHO               (RESBASE+5)
#define IDS_HELP_CMD_PATH               (RESBASE+6)
#define IDS_HELP_CMD_PWD                (RESBASE+7)
#define IDS_HELP_START                  (RESBASE+8)
#define IDS_HELP_END                    (RESBASE+9)
#define IDS_HELP_CMD_CD                 (RESBASE+10)
#define IDS_ERROR_GENERAL_BADNAME       (RESBASE+11)
#define IDS_ERROR_GENERAL_NOTFOUND      (RESBASE+12)
#define IDS_ERROR_GENERAL_BADSTDIN      (RESBASE+13)
#define IDS_ERROR_GENERAL_BADSTDOUT     (RESBASE+14)
#define IDS_ERROR_GENERAL_DOUBLEOUT     (RESBASE+15)
#define IDS_ERROR_GENERAL_DOUBLEERR     (RESBASE+16)
#define IDS_ERROR_GENERAL_BADSTDERR     (RESBASE+17)
#define IDS_ERROR_GENERAL_CANTSTDIN     (RESBASE+18)
#define IDS_ERROR_GENERAL_CANTSTDOUT    (RESBASE+19)
#define IDS_ERROR_GENERAL_CANTSTDERR    (RESBASE+20)
#define IDS_ERROR_GENERAL_IOBROKEN      (RESBASE+21)
#define IDS_HELP_CMD_TYPE               (RESBASE+22)
#define IDS_ERROR_BADSYNTAX             (RESBASE+23)
#define IDS_ERROR_FNF                   (RESBASE+24)
#define IDS_HELP_CMD_MKDIR              (RESBASE+25)
#define IDS_HELP_CMD_MD                 (RESBASE+26)
#define IDS_HELP_CMD_CHDIR              (RESBASE+27)
#define IDS_ERROR_GENERAL_ALREADYEXISTS (RESBASE+28)
#define IDS_ERROR_MD_CANTMAKE           (RESBASE+29)
#define IDS_HELP_CMD_RD                 (RESBASE+30)
#define IDS_HELP_CMD_RMDIR              (RESBASE+31)
#define IDS_YES                         (RESBASE+32)
#define IDS_AREYOUSURE                  (RESBASE+33)
#define IDS_ERROR_CANTREMOVE            (RESBASE+34)
#define IDS_ERROR_RD_CANTREMOVE         (RESBASE+35)
#define IDS_HELP_CMD_DEL                (RESBASE+36)
#define IDS_HELP_CMD_DIR                (RESBASE+37)
#define IDS_ERROR_GENERAL_BADOPTION     (RESBASE+38)
#define IDS_ERROR_GENERAL_NONOPTION     (RESBASE+39)
#define IDS_ERROR_DEL_FNF               (RESBASE+40)
#define IDS_ERROR_DEL_TOOBIG            (RESBASE+41)
#define IDS_ERROR_GENERAL_PATHTOOBIG    (RESBASE+42)
#define IDS_DIR_HEADER                  (RESBASE+43)
#define IDS_DIR_FNF                     (RESBASE+44)
#define IDS_DIR_FOOTER                  (RESBASE+45)
#define IDS_MORE                        (RESBASE+46)
#define IDS_ANYKEY                      (RESBASE+47)
#define IDS_HELP_CMD_ATTRIB             (RESBASE+48)
#define IDS_ERROR_ATTRIB_CANT           (RESBASE+49)
#define IDS_HELP_CMD_ERASE              (RESBASE+50)
#define IDS_HELP_EXT_EXIT               (RESBASE+51)
#define IDS_HELP_EXT_HELP               (RESBASE+52)
#define IDS_HELP_EXT_SET                (RESBASE+53)
#define IDS_HELP_EXT_ECHO               (RESBASE+54)
#define IDS_HELP_EXT_PATH               (RESBASE+55)
#define IDS_HELP_EXT_PWD                (RESBASE+56)
#define IDS_HELP_EXT_CD                 (RESBASE+57)
#define IDS_HELP_EXT_TYPE               (RESBASE+58)
#define IDS_HELP_EXT_MD                 (RESBASE+59)
#define IDS_HELP_EXT_RD                 (RESBASE+60)
#define IDS_HELP_EXT_DEL                (RESBASE+61)
#define IDS_HELP_EXT_DIR                (RESBASE+62)
#define IDS_HELP_EXT_ATTRIB             (RESBASE+63)
#define IDS_ERROR_HELP_NOTFOUND         (RESBASE+64)
#define IDS_ECHOON                      (RESBASE+65)
#define IDS_ECHOOFF                     (RESBASE+66)
#define IDS_TIME_PREFIX                 (RESBASE+67)
#define IDS_TIME_POSTFIX                (RESBASE+68)
#define IDS_ERROR_TIME_BAD              (RESBASE+69)
#define IDS_HELP_CMD_TIME               (RESBASE+70)
#define IDS_HELP_EXT_TIME               (RESBASE+71)
#define IDS_DATE_PREFIX                 (RESBASE+72)
#define IDS_DATE_POSTFIX                (RESBASE+73)
#define IDS_ERROR_DATE_BAD              (RESBASE+74)
#define IDS_HELP_CMD_DATE               (RESBASE+75)
#define IDS_HELP_EXT_DATE               (RESBASE+76)
#define IDS_HELP_CMD_MOVE               (RESBASE+77)
#define IDS_HELP_EXT_MOVE               (RESBASE+78)
#define IDS_ERROR_MOVE_MULTSOURCES      (RESBASE+79)
#define IDS_ERROR_MOVE_CANT             (RESBASE+80)
#define IDS_HELP_CMD_RENAME             (RESBASE+81)
#define IDS_HELP_EXT_REN                (RESBASE+82)
#define IDS_HELP_CMD_REN                (RESBASE+83)
#define IDS_HELP_CMD_COPY               (RESBASE+84)
#define IDS_HELP_EXT_COPY               (RESBASE+85)
#define IDS_HELP_CMD_PROMPT             (RESBASE+86)
#define IDS_HELP_EXT_PROMPT             (RESBASE+87)
#define IDS_ERROR_GENERAL_CANTOPEN      (RESBASE+88)
#define IDS_ERROR_COPY_CANT             (RESBASE+89)
#define IDS_ERROR_GENERAL_IOFAILED      (RESBASE+90)
#define IDS_CMD_COPY_STATS              (RESBASE+91)
#define IDS_ERROR_BADPATH               (RESBASE+92)
#define IDS_ERROR_CANTEXECUTE           (RESBASE+93)
#define IDS_ERROR_DONTKNOWHOW           (RESBASE+94)
#define IDS_HELP_CMD_PAUSE              (RESBASE+95)
#define IDS_HELP_EXT_PAUSE              (RESBASE+96)
#define IDS_HELP_CMD_REM                (RESBASE+97)
#define IDS_HELP_EXT_REM                (RESBASE+98)
#define IDS_HELP_CMD_SHIFT              (RESBASE+99)
#define IDS_HELP_EXT_SHIFT              (RESBASE+100)
#define IDS_ERROR_PIPE_CANT             (RESBASE+101)
#define IDS_STARTMESSAGE                (RESBASE+102)
#define IDS_HELP_CMD_CALL               (RESBASE+103)
#define IDS_HELP_EXT_CALL               (RESBASE+104)
#define IDS_HELP_CMD_START              (RESBASE+105)
#define IDS_HELP_EXT_START              (RESBASE+106)
#define IDS_HELP_CMD_GOTO               (RESBASE+107)
#define IDS_HELP_EXT_GOTO               (RESBASE+108)
#define IDS_HELP_CMD_IF                 (RESBASE+109)
#define IDS_HELP_EXT_IF                 (RESBASE+110)
#define IDS_ERROR_IF_BADERRLEVEL        (RESBASE+111)
#define IDS_HELP_CMD_TITLE              (RESBASE+112)
#define IDS_HELP_EXT_TITLE              (RESBASE+113)
#define IDS_ERROR_START_CANT            (RESBASE+114)
#define IDS_ERROR_TITLE                 (RESBASE+115)
#define IDS_HELP_CMD_CLS                (RESBASE+116)
#define IDS_HELP_EXT_CLS                (RESBASE+117)
#define IDS_DATE_FORM1                  (RESBASE+118)
#define IDS_DATE_FORM2                  (RESBASE+119)
#define IDS_DATE_FORM3                  (RESBASE+120)
#define IDS_CMD_TITLE                   (RESBASE+121)
#define IDS_ERROR_MOVE_CANT1            (RESBASE+122)
#define IDS_ERROR_COPY_CANT1            (RESBASE+123)
#define IDS_ERROR_COPY_SELF             (RESBASE+124)
#define IDS_HELP_CMD                    (RESBASE+125)
#define IDS_DIR_FOOTER_GR               (RESBASE+126)
#define IDS_DIR_FOOTER_GU               (RESBASE+127)

#define IDI_MAIN_ICON                   1

