//
// Copyright (c) Microsoft Corporation.  All rights reserved.
//
//
// This source code is licensed under Microsoft Shared Source License
// Version 1.0 for Windows CE.
// For a copy of the license visit http://go.microsoft.com/fwlink/?LinkId=3223.
//
// To be included from ..\TestCases.h only

#pragma once

//
// Test function prototype
//
TESTPROCAPI LightTest(LPTESTCASEARGS pTestCaseArgs);

//
// Number of frames generated by each call to test function
//
#define D3DMQA_LIGHTTEST_FRAMECOUNT 1

//
// Test Ordinal Extents
//
#define D3DMQA_LIGHTTEST_COUNT                        84
#define D3DMQA_LIGHTTEST_BASE                        100
#define D3DMQA_LIGHTTEST_MAX                         (D3DMQA_LIGHTTEST_BASE+D3DMQA_LIGHTTEST_COUNT-1)
