//
// Copyright (c) Microsoft Corporation.  All rights reserved.
//
//
// This source code is licensed under Microsoft Shared Source License
// Version 1.0 for Windows CE.
// For a copy of the license visit http://go.microsoft.com/fwlink/?LinkId=3223.
//
// To be included from ..\TestCases.h only

#pragma once

//
// Test function prototype
//
TESTPROCAPI TexStageTest(LPTESTCASEARGS pTestCaseArgs);

//
// Number of frames generated by each call to test function
//
#define D3DMQA_TEXSTAGETEST_FRAMECOUNT 1

//
// Test Ordinal Extents
//
#define D3DMQA_TEXSTAGETEST_COUNT           368
#define D3DMQA_TEXSTAGETEST_BASE           4000
#define D3DMQA_TEXSTAGETEST_MAX            (D3DMQA_TEXSTAGETEST_BASE+D3DMQA_TEXSTAGETEST_COUNT-1)

#define D3DMQA_TEXSTAGEONEARGTEST_COUNT      64                     
#define D3DMQA_TEXSTAGEONEARGTEST_BASE     4000
#define D3DMQA_TEXSTAGEONEARGTEST_MAX      (D3DMQA_TEXSTAGEONEARGTEST_BASE+D3DMQA_TEXSTAGEONEARGTEST_COUNT-1)

#define D3DMQA_TEXSTAGETWOARGTEST_COUNT     208                   
#define D3DMQA_TEXSTAGETWOARGTEST_BASE     4064
#define D3DMQA_TEXSTAGETWOARGTEST_MAX      (D3DMQA_TEXSTAGETWOARGTEST_BASE+D3DMQA_TEXSTAGETWOARGTEST_COUNT-1)

#define D3DMQA_TEXSTAGETHREEARGTEST_COUNT    96                      
#define D3DMQA_TEXSTAGETHREEARGTEST_BASE   4272
#define D3DMQA_TEXSTAGETHREEARGTEST_MAX    (D3DMQA_TEXSTAGETHREEARGTEST_BASE+D3DMQA_TEXSTAGETHREEARGTEST_COUNT-1)
