// Copyright (c) 1999-2000 Microsoft Corporation.  All rights reserved.
//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by rnaapp.rc
//
#define IDS_DIAL_WITH_NUMBER            1
#define IDS_DIAL_NO_NUMBER              2
#define IDS_OPENING_PORT                3
#define IDS_CONNECTING_TO_HOST          4
#define IDS_CONNECTING_TO_HOST_RETRY    5
#define IDS_CONNECTING_DEVICE           6
#define IDS_DEVICE_CONNECTED            7
#define IDS_PHY_EST                     8
#define IDS_AUTH_USER                   9
#define IDS_AUTH_EVENT                  10
#define IDS_AUTH_ERROR_TITLE            11
#define IDS_AUTH_ERR_REST_HOUR          12
#define IDS_AUTH_ERR_ACCT_DISABLED      13
#define IDS_AUTH_ERR_PWD_EXP            14
#define IDS_AUTH_ERR_NO_DIALIN          15
#define IDS_AUTH_ERR_CHG_PWD            16
#define IDS_AUTH_ERR_UNKNOWN            17
#define IDS_AUTH_PROJ                   18
#define IDS_AUTH_RESP                   19
#define IDS_USER_AUTH                   20
#define IDS_CONNECTED                   21
#define IDS_DISCONNECTED                22
#define IDS_REM_NET                     23
#define IDS_DISCONNECT                  24
#define IDS_RASDIAL_ERR                 25
#define IDS_PREV_CONN                   26
#define IDS_NO_CARRIER                  27
#define IDS_NO_DIALTONE                 28
#define IDS_DEVICE_NOT_READY            29
#define IDS_LINE_BUSY                   30
#define IDS_NO_ANSWER                   31
#define IDS_CARRIER_DROPPED             32
#define IDS_PORT_NOT_AVAIL              33
#define IDS_INVALID_PARAMETER           34
#define IDS_CONNECTING_TO               35
#define IDS_CONNECTED_TO                36
#define IDS_DCC_NO_CARRIER				37
#define IDR_MAINMENU                    101
#define ID_MINIMIZE                     101
#define IDC_ENTRYNAME                   101
#define IDI_RNAAPP                      103
#define IDI_DIALUP                      105
#define IDI_DIRECTCC                    106
#define IDD_USERPWD                     107
#define IDD_USERPWD2                    108
#define IDD_DCCSTATUS                   110
#define IDD_DCCSTATUS2                  111
#define IDI_VPN							112
#define IDC_EDIT1                       1000
#define IDC_USERNAME                    1001
#define IDC_EDIT2                       1002
#define IDC_PASSWORD                    1003
#define IDC_DOMAIN                      1004
#define IDC_SAVEPASSWORD                1005
#define IDCONNECT                       1006
#define IDC_PHONELABEL                  1007
#define IDC_PHONE                       1008
#define IDC_DIALFROMLABEL               1009
#define IDC_DIALPROPERTIES              1010
#define IDDIALPROPERTIES                1010
#define IDC_CONNLABEL                   1011
#define IDC_DIALFROM                    1012
#define IDDISMISS                       1013
#define IDC_STATUSMSG                   1014
#define IDC_STATUSICON                  1016
#define IDC_CANCEL_TEXT                 1017
#define IDC_STATUS1						1018
#define IDC_STATUS2						1019
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        111
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1018
#define _APS_NEXT_SYMED_VALUE           107
#endif
#endif
