// ---------------------------------------------------------------------------
//
// Copyright (c) 1995-2000 Microsoft Corporation.  All rights reserved.
//
// Date:       02/22/96 (Created)
//
// ---------------------------------------------------------------------------
#if 0 // for mui stuff
#include <resbases.h>

#define LINE_ICON 1
#define IDS_MANUAL_DIAL_TERMINAL        (RESBASE+0)
#define IDS_PRE_DIAL_TERMINAL           (RESBASE+1)
#define IDS_POST_DIAL_TERMINAL          (RESBASE+2)
#else
#define LINE_ICON 1
#define IDS_MANUAL_DIAL_TERMINAL        301
#define IDS_PRE_DIAL_TERMINAL           302
#define IDS_POST_DIAL_TERMINAL          303
#endif				 
