//
// Copyright (c) Microsoft Corporation.  All rights reserved.
//
//
// Use of this source code is subject to the terms of the Microsoft shared
// source or premium shared source license agreement under which you licensed
// this source code. If you did not accept the terms of the license agreement,
// you are not authorized to use this source code. For the terms of the license,
// please see the license agreement between you and Microsoft or, if applicable,
// see the SOURCE.RTF on your install media or the root of your tools installation.
// THE SOURCE CODE IS PROVIDED "AS IS", WITH NO WARRANTIES OR INDEMNITIES.
//
#define _ORDINAL_memchr                                                     1
#define _ORDINAL_wcscat                                                     2
#define _ORDINAL_wcschr                                                     3
#define _ORDINAL_wcscmp                                                     4
#define _ORDINAL_wcscpy                                                     5
#define _ORDINAL_wcscspn                                                    6
#define _ORDINAL_wcslen                                                     7
#define _ORDINAL_wcsncat                                                    8
#define _ORDINAL_wcsncmp                                                    9
#define _ORDINAL_wcsncpy                                                    10
#define _ORDINAL__wcsnset                                                   11
#define _ORDINAL_wcspbrk                                                    12
#define _ORDINAL_wcsrchr                                                    13
#define _ORDINAL__wcsrev                                                    14
#define _ORDINAL__wcsset                                                    15
#define _ORDINAL_wcsspn                                                     16
#define _ORDINAL_wcsstr                                                     17
#define _ORDINAL__wcsdup                                                    18
#define _ORDINAL_wcstombs                                                   19
#define _ORDINAL_mbstowcs                                                   20
#define _ORDINAL_wcstok                                                     21
#define _ORDINAL__wtol                                                      22
#define _ORDINAL__wtoi64                                                    23
#define _ORDINAL_wcsftime                                                   24
#define _ORDINAL__wsplitpath_s                                              25
#define _ORDINAL__wmakepath_s                                               26
#define _ORDINAL_iswctype                                                   27
#define _ORDINAL_towlower                                                   28
#define _ORDINAL_towupper                                                   29
#define _ORDINAL__wcsnicmp                                                  30
#define _ORDINAL__wcsicmp                                                   31
#define _ORDINAL__wcslwr                                                    32
#define _ORDINAL__wcsupr                                                    33
#define _ORDINAL_sscanf                                                     34
#define _ORDINAL_sprintf                                                    35
#define _ORDINAL_vfwprintf                                                  36
#define _ORDINAL__snprintf                                                  37
#define _ORDINAL_fwscanf                                                    38
#define _ORDINAL_fwprintf                                                   39
#define _ORDINAL_abs                                                        40
#define _ORDINAL_acos                                                       41
#define _ORDINAL_asin                                                       42
#define _ORDINAL_atan                                                       43
#define _ORDINAL_atan2                                                      44
#define _ORDINAL_atoi                                                       45
#define _ORDINAL_atol                                                       46
#define _ORDINAL_atof                                                       47
#define _ORDINAL__atodbl                                                    48
#define _ORDINAL__atoflt                                                    49
#define _ORDINAL__cabs                                                      50
#define _ORDINAL_ceil                                                       51
#define _ORDINAL__chgsign                                                   52
#define _ORDINAL__clearfp                                                   53
#define _ORDINAL__controlfp                                                 54
#define _ORDINAL__copysign                                                  55
#define _ORDINAL_cos                                                        56
#define _ORDINAL_cosh                                                       57
#define _ORDINAL_difftime                                                   58
#define _ORDINAL_div                                                        59
#define _ORDINAL__ecvt                                                      60
#define _ORDINAL_exp                                                        61
#define _ORDINAL_fabs                                                       62
#define _ORDINAL__fcvt                                                      63
#define _ORDINAL__finite                                                    64
#define _ORDINAL_floor                                                      65
#define _ORDINAL_fmod                                                       66
#define _ORDINAL__fpclass                                                   67
#define _ORDINAL__fpieee_flt                                                68
#define _ORDINAL__fpreset                                                   69
#define _ORDINAL_free                                                       70
#define _ORDINAL_frexp                                                      71
#define _ORDINAL__frnd                                                      72
#define _ORDINAL__fsqrt                                                     73
#define _ORDINAL__gcvt                                                      74
#define _ORDINAL__hypot                                                     75
#define _ORDINAL__isnan                                                     76
#define _ORDINAL__itoa                                                      77
#define _ORDINAL__itow                                                      78
#define _ORDINAL__j0                                                        79
#define _ORDINAL__j1                                                        80
#define _ORDINAL__jn                                                        81
#define _ORDINAL_labs                                                       82
#define _ORDINAL_ldexp                                                      83
#define _ORDINAL_ldiv                                                       84
#define _ORDINAL_log                                                        85
#define _ORDINAL_log10                                                      86
#define _ORDINAL__logb                                                      87
#define _ORDINAL_longjmp                                                    88
#define _ORDINAL__lrotl                                                     89
#define _ORDINAL__lrotr                                                     90
#define _ORDINAL__ltoa                                                      91
#define _ORDINAL__ltow                                                      92
#define _ORDINAL_malloc                                                     93
#define _ORDINAL__memccpy                                                   94
#define _ORDINAL_memcmp                                                     95
#define _ORDINAL_memcpy                                                     96
#define _ORDINAL__memicmp                                                   97
#define _ORDINAL_memmove                                                    98
#define _ORDINAL_memset                                                     99
#define _ORDINAL_modf                                                       100
#define _ORDINAL__msize                                                     101
#define _ORDINAL__nextafter                                                 102
#define _ORDINAL_pow                                                        103
#define _ORDINAL_qsort                                                      104
#define _ORDINAL_rand                                                       105
#define _ORDINAL_realloc                                                    106
#define _ORDINAL__rotl                                                      107
#define _ORDINAL__rotr                                                      108
#define _ORDINAL__scalb                                                     109
#define _ORDINAL_sin                                                        110
#define _ORDINAL_sinh                                                       111
#define _ORDINAL_sqrt                                                       112
#define _ORDINAL_srand                                                      113
#define _ORDINAL__statusfp                                                  114
#define _ORDINAL_strcat                                                     115
#define _ORDINAL_strchr                                                     116
#define _ORDINAL_strcmp                                                     117
#define _ORDINAL_strcpy                                                     118
#define _ORDINAL_strcspn                                                    119
#define _ORDINAL_strlen                                                     120
#define _ORDINAL_strncat                                                    121
#define _ORDINAL_strncmp                                                    122
#define _ORDINAL_strncpy                                                    123
#define _ORDINAL_strstr                                                     124
#define _ORDINAL_strtok                                                     125
#define _ORDINAL__swab                                                      126
#define _ORDINAL_tan                                                        127
#define _ORDINAL_tanh                                                       128
#define _ORDINAL__ultoa                                                     129
#define _ORDINAL__ultow                                                     130
#define _ORDINAL_wcstod                                                     131
#define _ORDINAL_wcstol                                                     132
#define _ORDINAL_wcstoul                                                    133
#define _ORDINAL__y0                                                        134
#define _ORDINAL__y1                                                        135
#define _ORDINAL__yn                                                        136
#define _ORDINAL__ld12tod                                                   137
#define _ORDINAL__ld12tof                                                   138
#define _ORDINAL___strgtold12                                               139
#define _ORDINAL_tolower                                                    140
#define _ORDINAL_toupper                                                    141
#define _ORDINAL__purecall                                                  142
#define _ORDINAL__fltused                                                   143
#define _ORDINAL_operator_delete                                            144
#define _ORDINAL_operator_new                                               145
#define _ORDINAL__snwprintf                                                 146
#define _ORDINAL__swprintf                                                  147
#define _ORDINAL_swscanf                                                    148
#define _ORDINAL_vswprintf                                                  149
#define _ORDINAL__getstdfilex                                               150
#define _ORDINAL_scanf                                                      151
#define _ORDINAL_printf                                                     152
#define _ORDINAL_vprintf                                                    153
#define _ORDINAL_getchar                                                    154
#define _ORDINAL_putchar                                                    155
#define _ORDINAL_gets                                                       156
#define _ORDINAL_puts                                                       157
#define _ORDINAL_fgetc                                                      158
#define _ORDINAL_fgets                                                      159
#define _ORDINAL_fputc                                                      160
#define _ORDINAL_fputs                                                      161
#define _ORDINAL_ungetc                                                     162
#define _ORDINAL_fopen                                                      163
#define _ORDINAL_fscanf                                                     164
#define _ORDINAL_fprintf                                                    165
#define _ORDINAL_vfprintf                                                   166
#define _ORDINAL__wfdopen                                                   167
#define _ORDINAL_fclose                                                     168
#define _ORDINAL__fcloseall                                                 169
#define _ORDINAL_fread                                                      170
#define _ORDINAL_fwrite                                                     171
#define _ORDINAL_fflush                                                     172
#define _ORDINAL__flushall                                                  173
#define _ORDINAL__fileno                                                    174
#define _ORDINAL_feof                                                       175
#define _ORDINAL_ferror                                                     176
#define _ORDINAL_clearerr                                                   177
#define _ORDINAL_fgetpos                                                    178
#define _ORDINAL_fsetpos                                                    179
#define _ORDINAL_fseek                                                      180
#define _ORDINAL_ftell                                                      181
#define _ORDINAL__vsnwprintf                                                182
#define _ORDINAL_wscanf                                                     183
#define _ORDINAL_wprintf                                                    184
#define _ORDINAL_vwprintf                                                   185
#define _ORDINAL_getwchar                                                   186
#define _ORDINAL_putwchar                                                   187
#define _ORDINAL__getws                                                     188
#define _ORDINAL__putws                                                     189
#define _ORDINAL_fgetwc                                                     190
#define _ORDINAL_fputwc                                                     191
#define _ORDINAL_ungetwc                                                    192
#define _ORDINAL_fgetws                                                     193
#define _ORDINAL_fputws                                                     194
#define _ORDINAL__wfopen                                                    195
#define _ORDINAL_vsprintf                                                   196
#define _ORDINAL__vsnprintf                                                 197
#define _ORDINAL__HUGE                                                      198
#define _ORDINAL__setmode                                                   199
#define _ORDINAL__wfreopen                                                  200
#define _ORDINAL_calloc                                                     201
#define _ORDINAL_strtod                                                     202
#define _ORDINAL_strtol                                                     203
#define _ORDINAL_strtoul                                                    204
#define _ORDINAL_strpbrk                                                    205
#define _ORDINAL_strrchr                                                    206
#define _ORDINAL_strspn                                                     207
#define _ORDINAL__strdup                                                    208
#define _ORDINAL__stricmp                                                   209
#define _ORDINAL__strnicmp                                                  210
#define _ORDINAL__strnset                                                   211
#define _ORDINAL__strrev                                                    212
#define _ORDINAL__strset                                                    213
#define _ORDINAL__strlwr                                                    214
#define _ORDINAL__strupr                                                    215
#define _ORDINAL__isctype                                                   216
#define _ORDINAL__atoi64                                                    217
#define _ORDINAL_operator_new_vector                                        218
#define _ORDINAL_operator_delete_vector                                     219
#define _ORDINAL___CxxFrameHandler                                          220
#define _ORDINAL__CxxThrowException                                         221
#define _ORDINAL_set_terminate                                              222
#define _ORDINAL_set_unexpected                                             223
#define _ORDINAL___set_inconsistency                                        224
#define _ORDINAL_terminate                                                  225
#define _ORDINAL_unexpected                                                 226
#define _ORDINAL__inconsistency                                             227
#define _ORDINAL___RTCastToVoid                                             228
#define _ORDINAL___RTtypeid                                                 229
#define _ORDINAL___RTDynamicCast                                            230
#define _ORDINAL_type_info_destructor                                       231
#define _ORDINAL_type_info_operator_eq                                      232
#define _ORDINAL_type_info_operator_ne                                      233
#define _ORDINAL_type_info_before                                           234
#define _ORDINAL_type_info_name                                             235
#define _ORDINAL_type_info_raw_name                                         236
#define _ORDINAL_type_info_constructor_copy                                 237
#define _ORDINAL_type_info_operator_assign                                  238
#define _ORDINAL_exception_constructor_default                              239
#define _ORDINAL_exception_constructor_char_ptr                             240
#define _ORDINAL_exception_constructor_copy                                 241
#define _ORDINAL_exception_operator_assign                                  242
#define _ORDINAL_exception_destructor                                       243
#define _ORDINAL_exception_what                                             244
#define _ORDINAL_eh_vector_constructor_iterator                             245
#define _ORDINAL_eh_vector_vbase_constructor_iterator                       246
#define _ORDINAL_eh_vector_destructor_iterator                              247
#define _ORDINAL_exception_vftable                                          248
#define _ORDINAL_typeinfo_vftable                                           249
#define _ORDINAL_setvbuf                                                    250
#define _ORDINAL__query_new_handler                                         251
#define _ORDINAL_set_new_handler                                            252
#define _ORDINAL__EH_prolog                                                 253
#define _ORDINAL__abs64                                                     254
#define _ORDINAL__byteswap_uint64                                           255
#define _ORDINAL__byteswap_ulong                                            256
#define _ORDINAL__byteswap_ushort                                           257
#define _ORDINAL__CountLeadingOnes                                          258
#define _ORDINAL__CountLeadingOnes64                                        259
#define _ORDINAL__CountLeadingSigns                                         260
#define _ORDINAL__CountLeadingSigns64                                       261
#define _ORDINAL__CountLeadingZeros                                         262
#define _ORDINAL__CountLeadingZeros64                                       263
#define _ORDINAL__CountOneBits                                              264
#define _ORDINAL__CountOneBits64                                            265
#define _ORDINAL__isnanf                                                    267
#define _ORDINAL__isunordered                                               268
#define _ORDINAL__isunorderedf                                              269
#define _ORDINAL__MulHigh                                                   270
#define _ORDINAL__MulUnsignedHigh                                           271
#define _ORDINAL__rotl64                                                    272
#define _ORDINAL__rotr64                                                    273
#define _ORDINAL_ceilf                                                      274
#define _ORDINAL_fabsf                                                      275
#define _ORDINAL_floorf                                                     276
#define _ORDINAL_fmodf                                                      277
#define _ORDINAL_sqrtf                                                      278
#define _ORDINAL__XcptFilter                                                279
#define _ORDINAL_operator_new_nothrow                                       280
#define _ORDINAL_nothrow                                                    281
#define _ORDINAL__set_new_mode                                              282
#define _ORDINAL__query_new_mode                                            283
#define _ORDINAL__set_new_handler                                           284
#define _ORDINAL__Xlen                                                      285
#define _ORDINAL__Xran                                                      286
#define _ORDINAL__Nomemory                                                  287
#define _ORDINAL_operator_new_vector_nothrow                                288
#define _ORDINAL_operator_delete_nothrow                                    289
#define _ORDINAL_operator_delete_vector_nothrow                             290
#define _ORDINAL___security_gen_cookie                                      291
#define _ORDINAL___report_gsfailure                                         292
#define _ORDINAL___report_gsfailure_context                                 293
#define _ORDINAL_uncaught_exception                                         294
#define _ORDINAL___CxxFrameHandler3                                         295
#define _ORDINAL_wcscat_s                                                   296
#define _ORDINAL_wcscpy_s                                                   297
#define _ORDINAL_wcsnlen                                                    298
#define _ORDINAL_wcsncat_s                                                  299
#define _ORDINAL_wcsncpy_s                                                  300
#define _ORDINAL__wcsnset_s                                                 301
#define _ORDINAL__wcsset_s                                                  302
#define _ORDINAL_wcstombs_s                                                 303
#define _ORDINAL_mbstowcs_s                                                 304
#define _ORDINAL_wcstok_s                                                   305
#define _ORDINAL__strnset_s                                                 306
#define _ORDINAL__strset_s                                                  307
#define _ORDINAL__strlwr_s                                                  308
#define _ORDINAL__strupr_s                                                  309
#define _ORDINAL__wcslwr_s                                                  310
#define _ORDINAL__wcsupr_s                                                  311
#define _ORDINAL__controlfp_s                                               312
#define _ORDINAL__ecvt_s                                                    313
#define _ORDINAL__fcvt_s                                                    314
#define _ORDINAL__itow_s                                                    315
#define _ORDINAL__gcvt_s                                                    316
#define _ORDINAL__itoa_s                                                    317
#define _ORDINAL__ltoa_s                                                    318
#define _ORDINAL__ltow_s                                                    319
#define _ORDINAL_memcpy_s                                                   320
#define _ORDINAL_memmove_s                                                  321
#define _ORDINAL_qsort_s                                                    322
#define _ORDINAL_rand_s                                                     323
#define _ORDINAL__recalloc                                                  324
#define _ORDINAL_strcat_s                                                   325
#define _ORDINAL_strcpy_s                                                   326
#define _ORDINAL_strnlen                                                    327
#define _ORDINAL_strncat_s                                                  328
#define _ORDINAL_strncpy_s                                                  329
#define _ORDINAL_strtok_s                                                   330
#define _ORDINAL__ultoa_s                                                   331
#define _ORDINAL__ultow_s                                                   332
#define _ORDINAL_swprintf_s                                                 333
#define _ORDINAL_vswprintf_s                                                334
#define _ORDINAL__snwprintf_s                                               335
#define _ORDINAL__vsnwprintf_s                                              336
#define _ORDINAL_sscanf_s                                                   337
#define _ORDINAL_sprintf_s                                                  338
#define _ORDINAL_vsprintf_s                                                 339
#define _ORDINAL__snprintf_s                                                340
#define _ORDINAL__vsnprintf_s                                               341
#define _ORDINAL_scanf_s                                                    342
#define _ORDINAL_printf_s                                                   343
#define _ORDINAL_vprintf_s                                                  344
#define _ORDINAL_gets_s                                                     345
#define _ORDINAL_fopen_s                                                    346
#define _ORDINAL_fscanf_s                                                   347
#define _ORDINAL_fprintf_s                                                  348
#define _ORDINAL_vfprintf_s                                                 349
#define _ORDINAL__wfreopen_s                                                350
#define _ORDINAL_fread_s                                                    351
#define _ORDINAL_clearerr_s                                                 352
#define _ORDINAL_swscanf_s                                                  353
#define _ORDINAL_wscanf_s                                                   354
#define _ORDINAL_wprintf_s                                                  355
#define _ORDINAL_vwprintf_s                                                 356
#define _ORDINAL__getws_s                                                   357
#define _ORDINAL__wfopen_s                                                  358
#define _ORDINAL_fwscanf_s                                                  359
#define _ORDINAL_fwprintf_s                                                 360
#define _ORDINAL_vfwprintf_s                                                361
#define _ORDINAL_eh_vector_copy_constructor_iterator                        362
#define _ORDINAL_eh_vector_vbase_copy_constructor_iterator                  363
#define _ORDINAL___security_gen_cookie2                                     364
#define _ORDINAL__set_invalid_parameter_handler                             365
#define _ORDINAL__get_invalid_parameter_handler                             366
#define _ORDINAL__invalid_parameter                                         367
#define _ORDINAL__scwprintf                                                 368
#define _ORDINAL__vscwprintf                                                369
#define _ORDINAL__scprintf                                                  370
#define _ORDINAL__vscprintf                                                 371
#define _ORDINAL_bsearch                                                    372
#define _ORDINAL_bsearch_s                                                  373
#define _ORDINAL__set_printf_count_output                                   374
#define _ORDINAL__get_printf_count_output                                   375
#define _ORDINAL__strtoui64                                                 376
#define _ORDINAL__wcstoi64                                                  377
#define _ORDINAL__wcstoui64                                                 378
#define _ORDINAL__strtoi64                                                  379
#define _ORDINAL__wtoi                                                      380
#define _ORDINAL__wtof                                                      381
#define _ORDINAL__i64tow_s                                                  382
#define _ORDINAL__i64toa_s                                                  383
#define _ORDINAL__ui64tow_s                                                 384
#define _ORDINAL__ui64toa_s                                                 385

#define _ORDINAL__time64                                                    390
#define _ORDINAL__mktime64                                                  391
#define _ORDINAL__localtime64_s                                             392
#define _ORDINAL__gmtime64_s                                                393

//crtstsec.lib need these exported functions
#define _ORDINAL__set_error_mode                                            400
#define _ORDINAL__initp_misc_purevirt                                       401
#define _ORDINAL__initp_misc_invarg                                         402
#define _ORDINAL__initp_heap_handler                                        403
#define _ORDINAL__malloc_crt                                                404
#define _ORDINAL__dosmaperr                                                 405
#define _ORDINAL__errno                                                     406
#define _ORDINAL__invalid_parameter_noinfo                                  407 
#define _ORDINAL__fpmath                                                    408
#define _ORDINAL__invoke_watson                                             409
#define _ORDINAL__lock                                                      411
#define _ORDINAL__unlock                                                    412
#define _ORDINAL__mtinitlocks                                               413
#define _ORDINAL__mtdeletelocks                                             414
#define _ORDINAL__mtinitlocknum                                             415


/*++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Architecture-specific helpers (500 - 699)

------------------------------------------------------------------------------*/

/*++

Exception handling helpers


--*/

#if defined(_ARM_)

#define _ORDINAL___jump_unwind                                                500
#define _ORDINAL___C_specific_handler                                         501

#elif defined(_X86_)

#define _ORDINAL__seh_longjmp_unwind4                                         500
#define _ORDINAL__except_handler3                                             501
#define _ORDINAL__local_unwind2                                               502
#define _ORDINAL___abnormal_termination                                       503
#define _ORDINAL__except_handler4_common                                      504

#endif // defined(_X86_)


#if defined(_ARM_)

/*++

ARM-specific helpers

--*/

#define _ORDINAL___rt_sdiv64by64                                            520
#define _ORDINAL___rt_srem64by64                                            521
#define _ORDINAL___rt_udiv64by64                                            522
#define _ORDINAL___rt_urem64by64                                            523
#define _ORDINAL___rt_sdiv                                                  524
#define _ORDINAL___rt_sdiv10                                                525
#define _ORDINAL___rt_udiv                                                  526
#define _ORDINAL___rt_udiv10                                                527
#define _ORDINAL___rt_srsh                                                  528
#define _ORDINAL___rt_ursh                                                  529
#define _ORDINAL___utod                                                     530
#define _ORDINAL___u64tos                                                   531
#define _ORDINAL___u64tod                                                   532
#define _ORDINAL___subs                                                     533
#define _ORDINAL___subd                                                     534
#define _ORDINAL___stou64                                                   535
#define _ORDINAL___stou                                                     536
#define _ORDINAL___stoi64                                                   537
#define _ORDINAL___stoi                                                     538
#define _ORDINAL___stod                                                     539
#define _ORDINAL___nes                                                      540
#define _ORDINAL___negs                                                     541
#define _ORDINAL___negd                                                     542
#define _ORDINAL___ned                                                      543
#define _ORDINAL___muls                                                     544
#define _ORDINAL___muld                                                     545
#define _ORDINAL___lts                                                      546
#define _ORDINAL___ltd                                                      547
#define _ORDINAL___les                                                      548
#define _ORDINAL___led                                                      549
#define _ORDINAL___itos                                                     550
#define _ORDINAL___itod                                                     551
#define _ORDINAL___i64tos                                                   552
#define _ORDINAL___i64tod                                                   553
#define _ORDINAL___gts                                                      554
#define _ORDINAL___gtd                                                      555
#define _ORDINAL___ges                                                      556
#define _ORDINAL___ged                                                      557
#define _ORDINAL___eqs                                                      558
#define _ORDINAL___eqd                                                      559
#define _ORDINAL___dtou64                                                   560
#define _ORDINAL___dtou                                                     561
#define _ORDINAL___dtos                                                     562
#define _ORDINAL___dtoi64                                                   563
#define _ORDINAL___dtoi                                                     564
#define _ORDINAL___divs                                                     565
#define _ORDINAL___divd                                                     567
#define _ORDINAL___cmps                                                     568
#define _ORDINAL___cmpd                                                     569
#define _ORDINAL___adds                                                     570
#define _ORDINAL___utos                                                     571
#define _ORDINAL___addd                                                     572
#define _ORDINAL_setjmp                                                     573
#define _ORDINAL__mbmemset                                                  574
#define _ORDINAL___rt_udiv64                                                575
#define _ORDINAL___rt_sdiv64                                                576
#define _ORDINAL___chkstk                                                   577
#define _ORDINAL__hypotf                                                    578
#define _ORDINAL__logbf                                                     579 
#define _ORDINAL_acosf                                                      580                       
#define _ORDINAL_asinf                                                      581
#define _ORDINAL_atan2f                                                     582
#define _ORDINAL_atanf                                                      583 
#define _ORDINAL_cosf                                                       584
#define _ORDINAL_coshf                                                      585
#define _ORDINAL_expf                                                       586   
#define _ORDINAL_log10f                                                     587
#define _ORDINAL_logf                                                       588
#define _ORDINAL_modff                                                      589
#define _ORDINAL_powf                                                       590   
#define _ORDINAL_sinf                                                       591
#define _ORDINAL_sinhf                                                      592
#define _ORDINAL_tanf                                                       593  
#define _ORDINAL_tanhf                                                      594 
#define _ORDINAL__FPE_Raise                                                 595  
#define _ORDINAL__memcpy_strict_align                                       596

#elif defined(_X86_)

/*++

x86-specific helpers

--*/

#define _ORDINAL__setjmp3                                                   520
#define _ORDINAL__alldiv                                                    521
#define _ORDINAL__allmul                                                    522
#define _ORDINAL__allrem                                                    523
#define _ORDINAL__allshr                                                    524
#define _ORDINAL__allshl                                                    525
#define _ORDINAL__aulldiv                                                   526
#define _ORDINAL__aullshr                                                   527
#define _ORDINAL__aullrem                                                   528
#define _ORDINAL__chkstk                                                    529
#define _ORDINAL__alloca_probe                                              530
#define _ORDINAL__CIsqrt                                                    531
#define _ORDINAL__CIpow                                                     532
#define _ORDINAL__CIlog                                                     533
#define _ORDINAL__CIlog10                                                   534
#define _ORDINAL__CIexp                                                     535
#define _ORDINAL__CIsin                                                     536
#define _ORDINAL__CIcos                                                     537
#define _ORDINAL__CItan                                                     538
#define _ORDINAL__CIasin                                                    539
#define _ORDINAL__CIacos                                                    540
#define _ORDINAL__CIatan                                                    541
#define _ORDINAL__CIatan2                                                   542
#define _ORDINAL__CIsinh                                                    543
#define _ORDINAL__CIcosh                                                    544
#define _ORDINAL__CItanh                                                    545
#define _ORDINAL__CIfmod                                                    546
#define _ORDINAL__fload                                                     547
#define _ORDINAL__ftol                                                      548
#define _ORDINAL__inp                                                       549
#define _ORDINAL__inpw                                                      550
#define _ORDINAL__inpd                                                      551
#define _ORDINAL__outp                                                      552
#define _ORDINAL__outpw                                                     553
#define _ORDINAL__outpd                                                     554
#define _ORDINAL__alldvrm                                                   555
#define _ORDINAL__aulldvrm                                                  556
#define _ORDINAL__SEH_prolog                                                557
#define _ORDINAL__SEH_epilog                                                558
#define _ORDINAL__ftol2                                                     559
#define _ORDINAL__EH_prolog2                                                560
#define _ORDINAL__alloca_probe_8                                            561
#define _ORDINAL__alloca_probe_16                                           562
#define _ORDINAL__ftol2_sse                                                 563
#define _ORDINAL__ftol2_sse_excpt                                           564
#define _ORDINAL__local_unwind4                                             565

#define _ORDINAL___libm_sse2_acosf                                          566 
#define _ORDINAL___libm_sse2_acos                                           567
#define _ORDINAL__libm_sse2_acos_precise                                    568 
#define _ORDINAL___libm_sse2_asinf                                          569
#define _ORDINAL___libm_sse2_asin                                           570 
#define _ORDINAL__libm_sse2_asin_precise                                    571
#define _ORDINAL___libm_sse2_atan2                                          572  
#define _ORDINAL___libm_sse2_atanf                                          573
#define _ORDINAL___libm_sse2_atan                                           574   
#define _ORDINAL__libm_sse2_atan_precise                                    575  
#define _ORDINAL___libm_sse2_cosf                                           576
#define _ORDINAL___libm_sse2_cos                                            577
#define _ORDINAL__libm_sse2_cos_precise                                     578  
#define _ORDINAL___libm_sse2_expf                                           579
#define _ORDINAL___libm_sse2_exp                                            580
#define _ORDINAL__libm_sse2_exp_precise                                     581
#define _ORDINAL___libm_sse2_log10f                                         582    
#define _ORDINAL___libm_sse2_log10                                          583 
#define _ORDINAL__libm_sse2_log10_precise                                   584 
#define _ORDINAL___libm_sse2_logf                                           585 
#define _ORDINAL___libm_sse2_log                                            586 
#define _ORDINAL__libm_sse2_log_precise                                     587    
#define _ORDINAL___libm_sse2_powf                                           588
#define _ORDINAL___libm_sse2_pow                                            589
#define _ORDINAL__libm_sse2_pow_precise                                     590 
#define _ORDINAL___libm_sse2_sincosf                                        591    
#define _ORDINAL___libm_sse2_sincos                                         592  
#define _ORDINAL___libm_sse2_sinf                                           593 
#define _ORDINAL___libm_sse2_sin                                            594
#define _ORDINAL__libm_sse2_sin_precise                                     595  
#define _ORDINAL__libm_sse2_sqrt_precise                                    596       
#define _ORDINAL___libm_sse2_tanf                                           597
#define _ORDINAL___libm_sse2_tan                                            598 
#define _ORDINAL__libm_sse2_tan_precise                                     599

#endif // defined(_X86_)

// exports from VS11 msvcrt
#define _ORDINAL____lc_codepage_func					1001
#define _ORDINAL____lc_collate_cp_func					1002
#define _ORDINAL____lc_locale_name_func					1003
#define _ORDINAL____mb_cur_max_func					1004
#define _ORDINAL____mb_cur_max_l_func					1005
#define _ORDINAL____setlc_active_func					1006
#define _ORDINAL____unguarded_readlc_active_add_func			1007
#define _ORDINAL___AdjustPointer					1008
#define _ORDINAL___badioinfo						1011
#define _ORDINAL___BuildCatchObject					1012
#define _ORDINAL___BuildCatchObjectHelper				1013
#define _ORDINAL___clean_type_info_names_internal			1014
#if defined(_X86_)
#define _ORDINAL___control87_2						1015
#endif 
#define _ORDINAL___CppXcptFilter					1016
#define _ORDINAL___create_locale					1017
#define _ORDINAL___crtCompareStringA					1018
#define _ORDINAL___crtCompareStringEx					1019
#define _ORDINAL___crtCompareStringW					1020
//#define _ORDINAL___crtCreateSemaphoreExW@24				1021
#define _ORDINAL___crtCreateSymbolicLinkW				1022
#define _ORDINAL___crtDecodePointer					1023
#define _ORDINAL___crtEncodePointer					1024
#define _ORDINAL___crtEnumSystemLocalesEx				1025
#define _ORDINAL___crtFlsAlloc						1026
#define _ORDINAL___crtFlsFree						1027
#define _ORDINAL___crtGetDateFormatEx					1028
#define _ORDINAL___crtGetLocaleInfoEx					1029
#define _ORDINAL___crtGetModuleFileNameA				1030
#define _ORDINAL___crtGetShowWindowMode					1031
#define _ORDINAL___crtGetTimeFormatEx					1032
#define _ORDINAL___crtGetUserDefaultLocaleName				1033
#define _ORDINAL___crtInitializeCriticalSectionEx			1034
#define _ORDINAL___crtInitOnceExecuteOnce				1035
#define _ORDINAL___crtIsPackagedApp					1036
#define _ORDINAL___crtIsValidLocaleName					1037
#define _ORDINAL___crtLCMapStringA					1038
#define _ORDINAL___crtLCMapStringEx					1039
#define _ORDINAL___crtLCMapStringW					1040
#define _ORDINAL___crtSetThreadStackGuarantee				1041
#define _ORDINAL___crtSetUnhandledExceptionFilter			1042
#if defined(_X86_)
#define _ORDINAL___crtTerminateProcess					1043
#define _ORDINAL___crtUnhandledException				1044
#endif 
#define _ORDINAL___CxxDetectRethrow					1045
#define _ORDINAL___CxxExceptionFilter					1046
#if defined(_X86_)
#define _ORDINAL___CxxLongjmpUnwind                                     1048
#endif 
#define _ORDINAL___CxxQueryExceptionSize				1049
#define _ORDINAL___CxxRegisterExceptionObject				1050
#define _ORDINAL___CxxUnregisterExceptionObject				1051
#define _ORDINAL___daylight						1052
#define _ORDINAL___DestructExceptionObject				1053
#define _ORDINAL___dllonexit						1054
#define _ORDINAL___doserrno						1055
#define _ORDINAL___dstbias						1056
#define _ORDINAL___fpecode						1057
#define _ORDINAL___FrameUnwindFilter					1058
#define _ORDINAL___free_locale						1059
#define _ORDINAL___get_current_locale					1060
#define _ORDINAL___get_flsindex						1061
#define _ORDINAL___getmainargs						1062
#define _ORDINAL___isascii						1064
#define _ORDINAL___iscsym						1065
#define _ORDINAL___iscsymf						1066
#define _ORDINAL___iswcsym						1067
#define _ORDINAL___iswcsymf						1068
#define _ORDINAL___lconv						1069
#define _ORDINAL___lconv_init						1070
#define _ORDINAL___mb_cur_max						1071
#define _ORDINAL___p___initenv						1072
#define _ORDINAL___p___wargv						1074
#define _ORDINAL___p___winitenv						1075
#define _ORDINAL___p__acmdln						1076
#define _ORDINAL___p__commode						1077
#define _ORDINAL___p__daylight						1078
#define _ORDINAL___p__dstbias						1079
#define _ORDINAL___p__environ						1080
#define _ORDINAL___p__fmode						1081
#define _ORDINAL___p__iob						1082
#define _ORDINAL___p__mbcasemap						1083
#define _ORDINAL___p__mbctype						1084
#define _ORDINAL___p__pgmptr						1086
#define _ORDINAL___p__pwctype						1087
#define _ORDINAL___p__timezone						1088
#define _ORDINAL___p__tzname						1089
#define _ORDINAL___p__wcmdln						1090
#define _ORDINAL___p__wenviron						1091
#define _ORDINAL___p__wpgmptr						1092
#define _ORDINAL___pctype_func						1093
#define _ORDINAL___pioinfo						1094
#define _ORDINAL___pwctype_func						1095
#define _ORDINAL___pxcptinfoptrs					1096
#define _ORDINAL___set_app_type						1097
#define _ORDINAL___setusermatherr					1098
#define _ORDINAL___STRINGTOLD						1099
#define _ORDINAL___STRINGTOLD_L						1100
#define _ORDINAL___strncnt						1101
#define _ORDINAL___sys_errlist						1102
#define _ORDINAL___sys_nerr						1103
#define _ORDINAL___threadhandle						1104
#define _ORDINAL___threadid						1105
#define _ORDINAL___timezone						1106
#define _ORDINAL___toascii						1107
#define _ORDINAL___TypeMatch						1108
#define _ORDINAL___tzname						1109
#define _ORDINAL___unDName						1110
#define _ORDINAL___unDNameEx						1111
#define _ORDINAL___unDNameHelper					1112
#define _ORDINAL___wcserror						1114
#define _ORDINAL___wcserror_s						1115
#define _ORDINAL___wcsncnt						1116
#define _ORDINAL___wgetmainargs						1117
#define _ORDINAL__abnormal_termination					1119
#define _ORDINAL__access						1120
#define _ORDINAL__access_s						1121
#define _ORDINAL__acmdln						1122
#define _ORDINAL__aligned_free						1123
#define _ORDINAL__aligned_malloc					1124
#define _ORDINAL__aligned_msize						1125
#define _ORDINAL__aligned_offset_malloc					1126
#define _ORDINAL__aligned_offset_realloc				1127
#define _ORDINAL__aligned_offset_recalloc				1128
#define _ORDINAL__aligned_realloc					1129
#define _ORDINAL__aligned_recalloc					1130
#define _ORDINAL__amsg_exit						1131
#define _ORDINAL__assert                        1132
#define _ORDINAL__atodbl_l						1133
#define _ORDINAL__atof_l						1134
#define _ORDINAL__atoflt_l						1135
#define _ORDINAL__atoi_l						1136
#define _ORDINAL__atoi64_l						1137
#define _ORDINAL__atol_l						1138
#define _ORDINAL__atoldbl						1139
#define _ORDINAL__atoldbl_l						1140
#define _ORDINAL__beep							1141
#define _ORDINAL__beginthread						1142
#define _ORDINAL__beginthreadex						1143
#define _ORDINAL__c_exit						1144
#define _ORDINAL__callnewh						1145
#define _ORDINAL__calloc_crt						1146
#define _ORDINAL__cexit							1147
#define _ORDINAL__cgets							1148
#define _ORDINAL__cgets_s						1149
#define _ORDINAL__cgetws						1150
#define _ORDINAL__cgetws_s						1151
#define _ORDINAL__chdir							1152
#define _ORDINAL__chdrive						1153
#if defined(_X86_)
#define _ORDINAL__chkesp						1154
#endif 
#define _ORDINAL__chmod							1155
#define _ORDINAL__chsize						1156
#define _ORDINAL__chsize_s						1157
#define _ORDINAL__close							1158
#define _ORDINAL__commit						1159
#define _ORDINAL__commode						1160
#define _ORDINAL__configthreadlocale					1161
#define _ORDINAL__control87						1162
#define _ORDINAL__cprintf						1163
#define _ORDINAL__cprintf_l						1164
#define _ORDINAL__cprintf_p						1165
#define _ORDINAL__cprintf_p_l						1166
#define _ORDINAL__cprintf_s						1167
#define _ORDINAL__cprintf_s_l						1168
#define _ORDINAL__cputs							1169
#define _ORDINAL__cputws						1170
#define _ORDINAL__creat							1171
#define _ORDINAL__create_locale						1172
#define _ORDINAL__CreateFrameInfo					1173
#if defined(_X86_)
#define _ORDINAL__crt_debugger_hook					1174
#endif
#define _ORDINAL__CRT_RTC_INIT						1175
#define _ORDINAL__CRT_RTC_INITW						1176
#define _ORDINAL__cscanf						1177
#define _ORDINAL__cscanf_l						1178
#define _ORDINAL__cscanf_s						1179
#define _ORDINAL__cscanf_s_l						1170
#define _ORDINAL__ctime32						1181
#define _ORDINAL__ctime32_s						1182
#define _ORDINAL__ctime64						1183
#define _ORDINAL__ctime64_s						1184
#define _ORDINAL__cwait							1185
#define _ORDINAL__cwprintf						1186
#define _ORDINAL__cwprintf_l						1187
#define _ORDINAL__cwprintf_p						1188
#define _ORDINAL__cwprintf_p_l						1189
#define _ORDINAL__cwprintf_s						1190
#define _ORDINAL__cwprintf_s_l						1191
#define _ORDINAL__cwscanf						1192
#define _ORDINAL__cwscanf_l						1193
#define _ORDINAL__cwscanf_s						1194
#define _ORDINAL__cwscanf_s_l						1195
#define _ORDINAL__daylight						1196
#define _ORDINAL__dstbias						1197
#define _ORDINAL__dup							1198
#define _ORDINAL__dup2							1199
#define _ORDINAL__dupenv_s						1200
#define _ORDINAL__endthread						1201
#define _ORDINAL__endthreadex						1202
#define _ORDINAL__eof							1204
#define _ORDINAL__except_handler2					1205
#define _ORDINAL__exit							1214
#define _ORDINAL__expand						1215
#define _ORDINAL__fclose_nolock						1216
#define _ORDINAL__fdopen						1217
#define _ORDINAL__fflush_nolock						1218
#define _ORDINAL__filbuf						1219
#define _ORDINAL__filelength						1220
#define _ORDINAL__filelengthi64						1221
#define _ORDINAL__flsbuf						1232
#define _ORDINAL__fmode							1233
#define _ORDINAL__fprintf_l						1234
#define _ORDINAL__fprintf_p						1235
#define _ORDINAL__fprintf_p_l						1236
#define _ORDINAL__fprintf_s_l						1237
#define _ORDINAL__fread_nolock						1238
#define _ORDINAL__fread_nolock_s					1239
#define _ORDINAL__free_locale						1240
#define _ORDINAL__freea							1241
//#define _ORDINAL__freefls@4						1242
#define _ORDINAL__fscanf_l						1243
#define _ORDINAL__fscanf_s_l						1244
#define _ORDINAL__fseek_nolock						1245
#define _ORDINAL__fseeki64						1246
#define _ORDINAL__fseeki64_nolock					1247
#define _ORDINAL__fsopen						1248
#define _ORDINAL__fstat32						1249
#define _ORDINAL__fstat32i64						1250
#define _ORDINAL__fstat64						1251
#define _ORDINAL__fstat64i32						1252
#define _ORDINAL__ftell_nolock						1253
#define _ORDINAL__ftelli64						1254
#define _ORDINAL__ftelli64_nolock					1255
#define _ORDINAL__ftime32						1256
#define _ORDINAL__ftime32_s						1257
#define _ORDINAL__ftime64						1258
#define _ORDINAL__ftime64_s						1259
#define _ORDINAL__fullpath						1260
#define _ORDINAL__futime32						1261
#define _ORDINAL__futime64						1262
#define _ORDINAL__fwprintf_l						1263
#define _ORDINAL__fwprintf_p						1264
#define _ORDINAL__fwprintf_p_l						1265
#define _ORDINAL__fwprintf_s_l						1266
#define _ORDINAL__fwrite_nolock						1267
#define _ORDINAL__fwscanf_l						1268
#define _ORDINAL__fwscanf_s_l						1269
#define _ORDINAL__get_current_locale					1270
#define _ORDINAL__get_daylight						1271
#define _ORDINAL__get_doserrno						1272
#define _ORDINAL__get_dstbias						1273
#define _ORDINAL__get_errno						1274
#define _ORDINAL__get_fmode						1275
#define _ORDINAL__get_heap_handle					1276
#define _ORDINAL__get_osfhandle						1277
#define _ORDINAL__get_output_format					1278
#define _ORDINAL__get_pgmptr						1279
#define _ORDINAL__get_purecall_handler					1280
#define _ORDINAL__get_terminate						1281
#define _ORDINAL__get_timezone						1282
#define _ORDINAL__get_tzname						1283
#define _ORDINAL__get_unexpected					1284
#define _ORDINAL__get_wpgmptr						1285
#define _ORDINAL__getc_nolock						1286
#define _ORDINAL__getch							1287
#define _ORDINAL__getch_nolock						1288
#define _ORDINAL__getche						1289
#define _ORDINAL__getche_nolock						1290
#define _ORDINAL__getcwd						1291
#define _ORDINAL__Getdays						1292
#define _ORDINAL__getdcwd						1293
#define _ORDINAL__getdiskfree						1294
#define _ORDINAL__getdllprocaddr					1295
#define _ORDINAL__getdrive						1296
#define _ORDINAL__getdrives						1297
#define _ORDINAL__getmaxstdio						1298
#define _ORDINAL__getmbcp						1299
#define _ORDINAL__Getmonths						1300
#define _ORDINAL__getpid						1301
#define _ORDINAL__getptd						1302
#define _ORDINAL__getsystime						1303
#define _ORDINAL__Gettnames						1304
#define _ORDINAL__getw							1305
#define _ORDINAL__getwch						1306
#define _ORDINAL__getwch_nolock						1307
#define _ORDINAL__getwche						1308
#define _ORDINAL__getwche_nolock					1309
#define _ORDINAL__global_unwind2					1310
#define _ORDINAL__gmtime32						1311
#define _ORDINAL__gmtime32_s						1312
#define _ORDINAL__gmtime64						1313
#define _ORDINAL__heapadd						1314
#define _ORDINAL__heapchk						1315
#define _ORDINAL__heapmin						1316
#define _ORDINAL__heapset						1317
#define _ORDINAL__heapused						1318
#define _ORDINAL__heapwalk						1319
#define _ORDINAL__i64toa						1321
#define _ORDINAL__i64tow						1322
#define _ORDINAL__initptd						1323
#define _ORDINAL__initterm						1324
#define _ORDINAL__initterm_e						1325
#define _ORDINAL__invalid_parameter_noinfo_noreturn			1326
#define _ORDINAL__iob							1327
#define _ORDINAL__isalnum_l						1328
#define _ORDINAL__isalpha_l						1329
#define _ORDINAL__isatty						1330
#define _ORDINAL__iscntrl_l						1331
#define _ORDINAL__isctype_l						1332
#define _ORDINAL__isdigit_l						1333
#define _ORDINAL__IsExceptionObjectToBeDestroyed			1334
#define _ORDINAL__isgraph_l						1335
#define _ORDINAL__isleadbyte_l						1336
#define _ORDINAL__islower_l						1337
#define _ORDINAL__ismbbalnum						1338
#define _ORDINAL__ismbbalnum_l						1339
#define _ORDINAL__ismbbalpha						1340
#define _ORDINAL__ismbbalpha_l						1341
#define _ORDINAL__ismbbgraph						1342
#define _ORDINAL__ismbbgraph_l						1343
#define _ORDINAL__ismbbkalnum						1344
#define _ORDINAL__ismbbkalnum_l						1345
#define _ORDINAL__ismbbkana						1346
#define _ORDINAL__ismbbkana_l						1347
#define _ORDINAL__ismbbkprint						1348
#define _ORDINAL__ismbbkprint_l						1349
#define _ORDINAL__ismbbkpunct						1350
#define _ORDINAL__ismbbkpunct_l						1351
#define _ORDINAL__ismbblead						1352
#define _ORDINAL__ismbblead_l						1353
#define _ORDINAL__ismbbprint						1354
#define _ORDINAL__ismbbprint_l						1355
#define _ORDINAL__ismbbpunct						1356
#define _ORDINAL__ismbbpunct_l						1357
#define _ORDINAL__ismbbtrail						1358
#define _ORDINAL__ismbbtrail_l						1359
#define _ORDINAL__ismbcalnum						1360
#define _ORDINAL__ismbcalnum_l						1361
#define _ORDINAL__ismbcalpha						1362
#define _ORDINAL__ismbcalpha_l						1363
#define _ORDINAL__ismbcdigit						1364
#define _ORDINAL__ismbcdigit_l						1365
#define _ORDINAL__ismbcgraph						1366
#define _ORDINAL__ismbcgraph_l						1367
#define _ORDINAL__ismbchira						1368
#define _ORDINAL__ismbchira_l						1369
#define _ORDINAL__ismbckata						1370
#define _ORDINAL__ismbckata_l						1371
#define _ORDINAL__ismbcl0						1372
#define _ORDINAL__ismbcl0_l						1373
#define _ORDINAL__ismbcl1						1374
#define _ORDINAL__ismbcl1_l						1375
#define _ORDINAL__ismbcl2						1376
#define _ORDINAL__ismbcl2_l						1377
#define _ORDINAL__ismbclegal						1378
#define _ORDINAL__ismbclegal_l						1379
#define _ORDINAL__ismbclower						1380
#define _ORDINAL__ismbclower_l						1381
#define _ORDINAL__ismbcprint						1382
#define _ORDINAL__ismbcprint_l						1383
#define _ORDINAL__ismbcpunct						1384
#define _ORDINAL__ismbcpunct_l						1385
#define _ORDINAL__ismbcspace						1386
#define _ORDINAL__ismbcspace_l						1387
#define _ORDINAL__ismbcsymbol						1388
#define _ORDINAL__ismbcsymbol_l						1389
#define _ORDINAL__ismbcupper						1390
#define _ORDINAL__ismbcupper_l						1391
#define _ORDINAL__ismbslead						1392
#define _ORDINAL__ismbslead_l						1393
#define _ORDINAL__ismbstrail						1394
#define _ORDINAL__ismbstrail_l						1395
#define _ORDINAL__isprint_l						1396
#define _ORDINAL__ispunct_l						1397
#define _ORDINAL__isspace_l						1398
#define _ORDINAL__isupper_l						1399
#define _ORDINAL__iswalnum_l						1400
#define _ORDINAL__iswalpha_l						1401
#define _ORDINAL__iswcntrl_l						1402
#define _ORDINAL__iswcsym_l						1403
#define _ORDINAL__iswcsymf_l						1404
#define _ORDINAL__iswdigit_l						1405
#define _ORDINAL__iswgraph_l						1406
#define _ORDINAL__iswlower_l						1407
#define _ORDINAL__iswprint_l						1408
#define _ORDINAL__iswpunct_l						1409
#define _ORDINAL__iswspace_l						1410
#define _ORDINAL__iswupper_l						1411
#define _ORDINAL__iswxdigit_l						1412
#define _ORDINAL__isxdigit_l						1413
#define _ORDINAL__kbhit							1414
#define _ORDINAL__lfind							1415
#define _ORDINAL__lfind_s						1416
#define _ORDINAL__localtime32						1418
#define _ORDINAL__localtime32_s						1419
#define _ORDINAL__localtime64						1420
#define _ORDINAL__lock_file						1421
#define _ORDINAL__Lock_shared_ptr_spin_lock				1422
#define _ORDINAL__locking						1423
#define _ORDINAL__longjmpex						1424
#define _ORDINAL__lsearch						1425
#define _ORDINAL__lsearch_s						1426
#define _ORDINAL__lseek							1427
#define _ORDINAL__lseeki64						1428
#define _ORDINAL__makepath						1429
#define _ORDINAL__makepath_s						1430
#define _ORDINAL__mbbtombc						1431
#define _ORDINAL__mbbtombc_l						1432
#define _ORDINAL__mbbtype						1433
#define _ORDINAL__mbbtype_l						1434
#define _ORDINAL__mbcasemap						1435
#define _ORDINAL__mbccpy						1436
#define _ORDINAL__mbccpy_l						1437
#define _ORDINAL__mbccpy_s						1438
#define _ORDINAL__mbccpy_s_l						1439
#define _ORDINAL__mbcjistojms						1440
#define _ORDINAL__mbcjistojms_l						1441
#define _ORDINAL__mbcjmstojis						1442
#define _ORDINAL__mbcjmstojis_l						1443
#define _ORDINAL__mbclen						1444
#define _ORDINAL__mbclen_l						1445
#define _ORDINAL__mbctohira						1446
#define _ORDINAL__mbctohira_l						1447
#define _ORDINAL__mbctokata						1448
#define _ORDINAL__mbctokata_l						1449
#define _ORDINAL__mbctolower						1450
#define _ORDINAL__mbctolower_l						1451
#define _ORDINAL__mbctombb						1452
#define _ORDINAL__mbctombb_l						1453
#define _ORDINAL__mbctoupper						1454
#define _ORDINAL__mbctoupper_l						1455
#define _ORDINAL__mbctype						1456
#define _ORDINAL__mblen_l						1457
#define _ORDINAL__mbsbtype						1458
#define _ORDINAL__mbsbtype_l						1459
#define _ORDINAL__mbscat_s						1460
#define _ORDINAL__mbscat_s_l						1461
#define _ORDINAL__mbschr						1462
#define _ORDINAL__mbschr_l						1463
#define _ORDINAL__mbscmp						1464
#define _ORDINAL__mbscmp_l						1465
#define _ORDINAL__mbscoll						1466
#define _ORDINAL__mbscoll_l						1467
#define _ORDINAL__mbscpy_s						1468
#define _ORDINAL__mbscpy_s_l						1469
#define _ORDINAL__mbscspn						1470
#define _ORDINAL__mbscspn_l						1471
#define _ORDINAL__mbsdec						1472
#define _ORDINAL__mbsdec_l						1473
#define _ORDINAL__mbsicmp						1474
#define _ORDINAL__mbsicmp_l						1475
#define _ORDINAL__mbsicoll						1476
#define _ORDINAL__mbsicoll_l						1477
#define _ORDINAL__mbsinc						1478
#define _ORDINAL__mbsinc_l						1479
#define _ORDINAL__mbslen						1480
#define _ORDINAL__mbslen_l						1481
#define _ORDINAL__mbslwr						1482
#define _ORDINAL__mbslwr_l						1483
#define _ORDINAL__mbslwr_s						1484
#define _ORDINAL__mbslwr_s_l						1485
#define _ORDINAL__mbsnbcat						1486
#define _ORDINAL__mbsnbcat_l						1487
#define _ORDINAL__mbsnbcat_s						1488
#define _ORDINAL__mbsnbcat_s_l						1489
#define _ORDINAL__mbsnbcmp						1490
#define _ORDINAL__mbsnbcmp_l						1491
#define _ORDINAL__mbsnbcnt						1492
#define _ORDINAL__mbsnbcnt_l						1493
#define _ORDINAL__mbsnbcoll						1494
#define _ORDINAL__mbsnbcoll_l						1495
#define _ORDINAL__mbsnbcpy						1496
#define _ORDINAL__mbsnbcpy_l						1497
#define _ORDINAL__mbsnbcpy_s						1498
#define _ORDINAL__mbsnbcpy_s_l						1499
#define _ORDINAL__mbsnbicmp						1500
#define _ORDINAL__mbsnbicmp_l						1501
#define _ORDINAL__mbsnbicoll						1502
#define _ORDINAL__mbsnbicoll_l						1503
#define _ORDINAL__mbsnbset						1504
#define _ORDINAL__mbsnbset_l						1505
#define _ORDINAL__mbsnbset_s						1506
#define _ORDINAL__mbsnbset_s_l						1507
#define _ORDINAL__mbsncat						1508
#define _ORDINAL__mbsncat_l						1509
#define _ORDINAL__mbsncat_s						1510
#define _ORDINAL__mbsncat_s_l						1511
#define _ORDINAL__mbsnccnt						1512
#define _ORDINAL__mbsnccnt_l						1513
#define _ORDINAL__mbsncmp						1514
#define _ORDINAL__mbsncmp_l						1515
#define _ORDINAL__mbsncoll						1516
#define _ORDINAL__mbsncoll_l						1517
#define _ORDINAL__mbsncpy						1518
#define _ORDINAL__mbsncpy_l						1519
#define _ORDINAL__mbsncpy_s						1520
#define _ORDINAL__mbsncpy_s_l						1521
#define _ORDINAL__mbsnextc						1522
#define _ORDINAL__mbsnextc_l						1523
#define _ORDINAL__mbsnicmp						1524
#define _ORDINAL__mbsnicmp_l						1525
#define _ORDINAL__mbsnicoll						1526
#define _ORDINAL__mbsnicoll_l						1527
#define _ORDINAL__mbsninc						1528
#define _ORDINAL__mbsninc_l						1529
#define _ORDINAL__mbsnlen						1530
#define _ORDINAL__mbsnlen_l						1531
#define _ORDINAL__mbsnset						1532
#define _ORDINAL__mbsnset_l						1533
#define _ORDINAL__mbsnset_s						1534
#define _ORDINAL__mbsnset_s_l						1535
#define _ORDINAL__mbspbrk						1536
#define _ORDINAL__mbspbrk_l						1537
#define _ORDINAL__mbsrchr						1538
#define _ORDINAL__mbsrchr_l						1539
#define _ORDINAL__mbsrev						1540
#define _ORDINAL__mbsrev_l						1541
#define _ORDINAL__mbsset						1542
#define _ORDINAL__mbsset_l						1543
#define _ORDINAL__mbsset_s						1544
#define _ORDINAL__mbsset_s_l						1545
#define _ORDINAL__mbsspn						1546
#define _ORDINAL__mbsspn_l						1547
#define _ORDINAL__mbsspnp						1548
#define _ORDINAL__mbsspnp_l						1549
#define _ORDINAL__mbsstr						1550
#define _ORDINAL__mbsstr_l						1551
#define _ORDINAL__mbstok						1552
#define _ORDINAL__mbstok_l						1553
#define _ORDINAL__mbstok_s						1554
#define _ORDINAL__mbstok_s_l						1555
#define _ORDINAL__mbstowcs_l						1556
#define _ORDINAL__mbstowcs_s_l						1557
#define _ORDINAL__mbstrlen						1558
#define _ORDINAL__mbstrlen_l						1559
#define _ORDINAL__mbstrnlen						1560
#define _ORDINAL__mbstrnlen_l						1561
#define _ORDINAL__mbsupr						1562
#define _ORDINAL__mbsupr_l						1563
#define _ORDINAL__mbsupr_s						1564
#define _ORDINAL__mbsupr_s_l						1565
#define _ORDINAL__mbtowc_l						1566
#define _ORDINAL__memicmp_l						1567
#define _ORDINAL__mkdir							1568
#define _ORDINAL__mkgmtime32						1569
#define _ORDINAL__mkgmtime64						1570
#define _ORDINAL__mktemp						1571
#define _ORDINAL__mktemp_s						1572
#define _ORDINAL__mktime32						1573
#define _ORDINAL__NLG_Return						1574
#if defined(_X86_)
#define _ORDINAL__NLG_Dispatch2						1575
#define _ORDINAL__NLG_Return2						1576
#endif 
#define _ORDINAL__onexit						1577
#define _ORDINAL__open							1578
#define _ORDINAL__open_osfhandle					1579
#define _ORDINAL__pctype						1581
#define _ORDINAL__pipe							1583
#define _ORDINAL__printf_l						1585
#define _ORDINAL__printf_p						1586
#define _ORDINAL__printf_p_l						1587
#define _ORDINAL__printf_s_l						1588
#define _ORDINAL__putch							1589
#define _ORDINAL__putch_nolock						1590
#define _ORDINAL__putenv						1591
#define _ORDINAL__putenv_s						1592
#define _ORDINAL__putw							1593
#define _ORDINAL__putwch						1594
#define _ORDINAL__putwch_nolock						1595
#define _ORDINAL__pwctype						1596
#define _ORDINAL__read							1597
#define _ORDINAL__realloc_crt						1598
#define _ORDINAL__recalloc_crt						1599
#define _ORDINAL__resetstkoflw						1600
#define _ORDINAL__rmdir							1601
#define _ORDINAL__rmtmp							1602
#define _ORDINAL__scanf_l						1603
#define _ORDINAL__scanf_s_l						1604
#define _ORDINAL__scprintf_l						1605
#define _ORDINAL__scprintf_p						1606
#define _ORDINAL__scprintf_p_l						1607
#define _ORDINAL__scwprintf_l						1608
#define _ORDINAL__scwprintf_p						1609
#define _ORDINAL__scwprintf_p_l						1610
#define _ORDINAL__searchenv						1611
#define _ORDINAL__searchenv_s						1612
//#define _ORDINAL__seh_longjmp_unwind@4					1613
//#define _ORDINAL__seh_longjmp_unwind4@4					1614
#define _ORDINAL__set_abort_behavior					1615
#define _ORDINAL__set_controlfp						1616
#define _ORDINAL__set_doserrno						1617
#define _ORDINAL__set_errno						1618
#define _ORDINAL__set_fmode						1619
#define _ORDINAL__set_malloc_crt_max_wait				1620
#define _ORDINAL__set_output_format					1621
#define _ORDINAL__set_purecall_handler					1622
#if defined(_X86_)
#define _ORDINAL__set_SSE2_enable					1623
#endif
#define _ORDINAL__seterrormode						1624
#define _ORDINAL__setjmp						1625
#define _ORDINAL__setmaxstdio						1626
#define _ORDINAL__setmbcp						1627
#define _ORDINAL__setsystime						1628
#define _ORDINAL__sleep							1629
#define _ORDINAL__snprintf_c						1630
#define _ORDINAL__snprintf_c_l						1631
#define _ORDINAL__snprintf_l						1632
#define _ORDINAL__snprintf_s_l						1633
#define _ORDINAL__snscanf						1634
#define _ORDINAL__snscanf_l						1635
#define _ORDINAL__snscanf_s						1636
#define _ORDINAL__snscanf_s_l						1637
#define _ORDINAL__snwprintf_l						1638
#define _ORDINAL__snwprintf_s_l						1639
#define _ORDINAL__snwscanf						1640
#define _ORDINAL__snwscanf_l						1641
#define _ORDINAL__snwscanf_s						1642
#define _ORDINAL__snwscanf_s_l						1643
#define _ORDINAL__sopen							1644
#define _ORDINAL__sopen_s						1645
#define _ORDINAL__splitpath						1654
#define _ORDINAL__splitpath_s						1655
#define _ORDINAL__sprintf_l						1656
#define _ORDINAL__sprintf_p						1657
#define _ORDINAL__sprintf_p_l						1658
#define _ORDINAL__sprintf_s_l						1659
#define _ORDINAL__sscanf_l						1660
#define _ORDINAL__sscanf_s_l						1661
#define _ORDINAL__stat32						1662
#define _ORDINAL__stat32i64						1663
#define _ORDINAL__stat64						1664
#define _ORDINAL__stat64i32						1665
#if defined(_X86_)
#define _ORDINAL__statusfp2						1666
#endif
#define _ORDINAL__strcoll_l						1667
#define _ORDINAL__strdate						1668
#define _ORDINAL__strdate_s						1669
#define _ORDINAL__strerror						1670
#define _ORDINAL__strerror_s						1671
#define _ORDINAL__Strftime						1672
#define _ORDINAL__strftime_l						1673
#define _ORDINAL__stricmp_l						1674
#define _ORDINAL__stricoll						1675
#define _ORDINAL__stricoll_l						1676
#define _ORDINAL__strlwr_l						1677
#define _ORDINAL__strlwr_s_l						1678
#define _ORDINAL__strncoll						1679
#define _ORDINAL__strncoll_l						1680
#define _ORDINAL__strnicmp_l						1681
#define _ORDINAL__strnicoll						1682
#define _ORDINAL__strnicoll_l						1683
#define _ORDINAL__strtime						1684
#define _ORDINAL__strtime_s						1685
#define _ORDINAL__strtod_l						1686
#define _ORDINAL__strtoi64_l						1687
#define _ORDINAL__strtol_l						1688
#define _ORDINAL__strtoui64_l						1689
#define _ORDINAL__strtoul_l						1690
#define _ORDINAL__strupr_l						1691
#define _ORDINAL__strupr_s_l						1692
#define _ORDINAL__strxfrm_l						1693
#define _ORDINAL__swscanf_l						1694
#define _ORDINAL__swscanf_s_l						1695
#define _ORDINAL__sys_errlist						1696
#define _ORDINAL__sys_nerr						1697
#define _ORDINAL__tell							1698
#define _ORDINAL__telli64						1699
#define _ORDINAL__tempnam						1700
#define _ORDINAL__time32						1701
#define _ORDINAL__timezone						1702
#define _ORDINAL__tolower						1703
#define _ORDINAL__tolower_l						1704
#define _ORDINAL__toupper						1705
#define _ORDINAL__toupper_l						1706
#define _ORDINAL__towlower_l						1707
#define _ORDINAL__towupper_l						1708
#define _ORDINAL__tzname						1709
#define _ORDINAL__tzset							1710
#define _ORDINAL__ui64toa						1711
#define _ORDINAL__ui64tow						1712
#define _ORDINAL__umask							1713
#define _ORDINAL__umask_s						1714
#define _ORDINAL__unlink						1715
#define _ORDINAL__unlock_file						1717
#define _ORDINAL__Unlock_shared_ptr_spin_lock				1718
#define _ORDINAL__utime32						1719
#define _ORDINAL__utime64						1720
#define _ORDINAL__vcprintf						1721
#define _ORDINAL__vcprintf_l						1722
#define _ORDINAL__vcprintf_p						1723
#define _ORDINAL__vcprintf_p_l						1724
#define _ORDINAL__vcprintf_s						1725
#define _ORDINAL__vcprintf_s_l						1726
#define _ORDINAL__vcwprintf						1727
#define _ORDINAL__vcwprintf_l						1728
#define _ORDINAL__vcwprintf_p						1729
#define _ORDINAL__vcwprintf_p_l						1730
#define _ORDINAL__vcwprintf_s						1731
#define _ORDINAL__vcwprintf_s_l						1732
#define _ORDINAL__vfprintf_l						1733
#define _ORDINAL__vfprintf_p						1734
#define _ORDINAL__vfprintf_p_l						1735
#define _ORDINAL__vfprintf_s_l						1736
#define _ORDINAL__vfwprintf_l						1737
#define _ORDINAL__vfwprintf_p						1738
#define _ORDINAL__vfwprintf_p_l						1739
#define _ORDINAL__vfwprintf_s_l						1740
#define _ORDINAL__vprintf_l						1741
#define _ORDINAL__vprintf_p						1742
#define _ORDINAL__vprintf_p_l						1743
#define _ORDINAL__vprintf_s_l						1744
#define _ORDINAL__vscprintf_l						1745
#define _ORDINAL__vscprintf_p						1746
#define _ORDINAL__vscprintf_p_l						1747
#define _ORDINAL__vscwprintf_l						1748
#define _ORDINAL__vscwprintf_p						1749
#define _ORDINAL__vscwprintf_p_l					1750
#define _ORDINAL__vsnprintf_c						1751
#define _ORDINAL__vsnprintf_c_l						1752
#define _ORDINAL__vsnprintf_l						1753
#define _ORDINAL__vsnprintf_s_l						1754
#define _ORDINAL__vsnwprintf_l						1755
#define _ORDINAL__vsnwprintf_s_l					1756
#define _ORDINAL__vsprintf_l						1757
#define _ORDINAL__vsprintf_p						1758
#define _ORDINAL__vsprintf_p_l						1759
#define _ORDINAL__vsprintf_s_l						1760
#define _ORDINAL__vwprintf_l						1761
#define _ORDINAL__vwprintf_p						1762
#define _ORDINAL__vwprintf_p_l						1763
#define _ORDINAL__vwprintf_s_l						1764
#define _ORDINAL__W_Getdays						1765
#define _ORDINAL__W_Getmonths						1766
#define _ORDINAL__W_Gettnames						1767
#define _ORDINAL__waccess						1768
#define _ORDINAL__waccess_s						1769
#define _ORDINAL__wasctime						1770
#define _ORDINAL__wasctime_s						1771
#define _ORDINAL__wassert						1772
#define _ORDINAL__wchdir						1773
#define _ORDINAL__wchmod						1774
#define _ORDINAL__wcmdln						1775
#define _ORDINAL__wcreat						1776
#define _ORDINAL__wcreate_locale					1777
#define _ORDINAL__wcscoll_l						1778
#define _ORDINAL__wcserror						1779
#define _ORDINAL__wcserror_s						1780
#define _ORDINAL__Wcsftime						1781
#define _ORDINAL__wcsftime_l						1782
#define _ORDINAL__wcsicmp_l						1783
#define _ORDINAL__wcsicoll						1784
#define _ORDINAL__wcsicoll_l						1785
#define _ORDINAL__wcslwr_l						1786
#define _ORDINAL__wcslwr_s_l						1787
#define _ORDINAL__wcsncoll						1788
#define _ORDINAL__wcsncoll_l						1789
#define _ORDINAL__wcsnicmp_l						1790
#define _ORDINAL__wcsnicoll						1791
#define _ORDINAL__wcsnicoll_l						1792
#define _ORDINAL__wcstod_l						1793
#define _ORDINAL__wcstoi64_l						1794
#define _ORDINAL__wcstol_l						1795
#define _ORDINAL__wcstombs_l						1796
#define _ORDINAL__wcstombs_s_l						1797
#define _ORDINAL__wcstoui64_l						1798
#define _ORDINAL__wcstoul_l						1799
#define _ORDINAL__wcsupr_l						1800
#define _ORDINAL__wcsupr_s_l						1801
#define _ORDINAL__wcsxfrm_l						1802
#define _ORDINAL__wctime32						1803
#define _ORDINAL__wctime32_s						1804
#define _ORDINAL__wctime64						1805
#define _ORDINAL__wctime64_s						1806
#define _ORDINAL__wctomb_l						1807
#define _ORDINAL__wctomb_s_l						1808
#define _ORDINAL__wctype						1809
#define _ORDINAL__wdupenv_s						1810
#define _ORDINAL__wfsopen						1828
#define _ORDINAL__wfullpath						1829
#define _ORDINAL__wgetcwd						1830
#define _ORDINAL__wgetdcwd						1831
#define _ORDINAL__wgetenv						1832
#define _ORDINAL__wgetenv_s						1833
#define _ORDINAL__wmakepath						1834
#define _ORDINAL__wmkdir						1835
#define _ORDINAL__wmktemp						1836
#define _ORDINAL__wmktemp_s						1837
#define _ORDINAL__wopen							1838
#define _ORDINAL__wperror						1839
#define _ORDINAL__wprintf_l						1842
#define _ORDINAL__wprintf_p						1843
#define _ORDINAL__wprintf_p_l						1844
#define _ORDINAL__wprintf_s_l						1845
#define _ORDINAL__wputenv						1846
#define _ORDINAL__wputenv_s						1847
#define _ORDINAL__wremove						1848
#define _ORDINAL__wrename						1849
#define _ORDINAL__write							1850
#define _ORDINAL__wrmdir						1851
#define _ORDINAL__wscanf_l						1852
#define _ORDINAL__wscanf_s_l						1853
#define _ORDINAL__wsearchenv						1854
#define _ORDINAL__wsearchenv_s						1855
#define _ORDINAL__wsetlocale						1856
#define _ORDINAL__wsopen						1857
#define _ORDINAL__wsopen_s						1858
#define _ORDINAL__wsplitpath						1867
#define _ORDINAL__wstat32						1868
#define _ORDINAL__wstat32i64						1869
#define _ORDINAL__wstat64						1870
#define _ORDINAL__wstat64i32						1871
#define _ORDINAL__wstrdate						1872
#define _ORDINAL__wstrdate_s						1873
#define _ORDINAL__wstrtime						1874
#define _ORDINAL__wstrtime_s						1875
#define _ORDINAL__wtempnam						1877
#define _ORDINAL__wtof_l						1880
#define _ORDINAL__wtoi_l						1881
#define _ORDINAL__wtoi64_l						1882
#define _ORDINAL__wtol_l						1883
#define _ORDINAL__wunlink						1884
#define _ORDINAL__wutime32						1885
#define _ORDINAL__wutime64						1886
#define _ORDINAL_abort							1887
#define _ORDINAL_asctime						1888
#define _ORDINAL_asctime_s						1889
#define _ORDINAL_atexit							1890
#define _ORDINAL_btowc							1891
#define _ORDINAL_clock							1892
#define _ORDINAL_exit							1893
#define _ORDINAL_freopen						1894
#define _ORDINAL_freopen_s						1895
#define _ORDINAL_getc							1896
#define _ORDINAL_getenv							1897
#define _ORDINAL_getenv_s						1898
#define _ORDINAL_getwc							1899
#define _ORDINAL_is_wctype						1900
#define _ORDINAL_isalnum						1901
#define _ORDINAL_isalpha						1902
#define _ORDINAL_iscntrl						1903
#define _ORDINAL_isdigit						1904
#define _ORDINAL_isgraph						1905
#define _ORDINAL_isleadbyte						1906
#define _ORDINAL_islower						1907
#define _ORDINAL_isprint						1908
#define _ORDINAL_ispunct						1909
#define _ORDINAL_isspace						1910
#define _ORDINAL_isupper						1911
#define _ORDINAL_iswalnum						1912
#define _ORDINAL_iswalpha						1913
#define _ORDINAL_iswascii						1914
#define _ORDINAL_iswcntrl						1915
#define _ORDINAL_iswdigit						1916
#define _ORDINAL_iswgraph						1917
#define _ORDINAL_iswlower						1918
#define _ORDINAL_iswprint						1919
#define _ORDINAL_iswpunct						1920
#define _ORDINAL_iswspace						1921
#define _ORDINAL_iswupper						1922
#define _ORDINAL_iswxdigit						1923
#define _ORDINAL_isxdigit						1924
#define _ORDINAL_llabs							1925
#define _ORDINAL_lldiv							1926
#define _ORDINAL_localeconv						1927
#define _ORDINAL_mbrtowc						1928
#define _ORDINAL_mbsrtowcs						1929
#define _ORDINAL_mbsrtowcs_s						1930
#define _ORDINAL_mbtowc							1931
#define _ORDINAL_perror							1932
#define _ORDINAL_putc							1933
#define _ORDINAL_putwc							1934
#define _ORDINAL_raise							1935
#define _ORDINAL_remove							1936
#define _ORDINAL_rename							1937
#define _ORDINAL_rewind							1938
#define _ORDINAL_setbuf							1939
#define _ORDINAL_setlocale						1940
#define _ORDINAL_signal							1941
#define _ORDINAL_strcoll						1942
#define _ORDINAL_strerror						1943
#define _ORDINAL_strerror_s						1944
#define _ORDINAL_strftime						1945
#define _ORDINAL_strxfrm						1946
#define _ORDINAL_wcrtomb						1952
#define _ORDINAL_wcrtomb_s						1953
#define _ORDINAL_wcscoll						1954
#define _ORDINAL_wcsrtombs						1955
#define _ORDINAL_wcsrtombs_s						1956
#define _ORDINAL_wcsxfrm						1957
#define _ORDINAL_wctob							1958
#define _ORDINAL_wctomb							1959
#define _ORDINAL_wctomb_s						1960
#define _ORDINAL_wmemcpy_s						1961
#define _ORDINAL_wmemmove_s						1962
#define _ORDINAL__fgetwchar                                             1963
#define _ORDINAL__fputwchar                                             1964
#define _ORDINAL_mblen                                                  1965
#define _ORDINAL__vswprintf_c_l                                         1966
#define _ORDINAL___iob_func                                             1967
#define _ORDINAL__CrtDbgReportW                                         1968
#define _ORDINAL__fgetwc_nolock                                         1969
#define _ORDINAL__fgetchar                                              1970 
#define _ORDINAL__fputwc_nolock                                         1971 
#define _ORDINAL__fputchar                                              1972
#define _ORDINAL__iswctype_l                                            1973   
#define _ORDINAL__swprintf_p                                            1974 
#define _ORDINAL__swprintf_p_l                                          1975
#define _ORDINAL__ungetc_nolock                                         1976  
#define _ORDINAL__ungetwc_nolock                                        1977 
#define _ORDINAL__vswprintf_p                                           1978
#define _ORDINAL__vswprintf_p_l                                         1979
#define _ORDINAL__difftime32                                            1980       
#define _ORDINAL_mbrlen                                                 1981 
#define _ORDINAL___swprintf_l                                           1982  
#define _ORDINAL__swprintf_s_l                                          1983
#define _ORDINAL___vswprintf_l                                          1984
#define _ORDINAL__vswprintf_l                                           1985   
#define _ORDINAL__vswprintf_s_l                                         1986   
