//+----------------------------------------------------------------------------
//
//
// File:
//      WISC.idl
//
// Contents:
//
//      WinInetConnector type library
//
//-----------------------------------------------------------------------------


import "oaidl.idl";

#include "ConnGuid.h"
#include "IdlUtils.h"
#include "SoapVer.h"

TYPE_LIBRARY(LIBID_WININETSOAPCONNECTOR, SOAP_SDK_VERSION, "WinInet Soap Connector Type Library")
library WinInetConnectorLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

};
