//
// Copyright (c) Microsoft Corporation.  All rights reserved.
//
//
// Use of this source code is subject to the terms of the Microsoft shared
// source or premium shared source license agreement under which you licensed
// this source code. If you did not accept the terms of the license agreement,
// you are not authorized to use this source code. For the terms of the license,
// please see the license agreement between you and Microsoft or, if applicable,
// see the SOURCE.RTF on your install media or the root of your tools installation.
// THE SOURCE CODE IS PROVIDED "AS IS", WITH NO WARRANTIES.
//
// To be included from ..\TestCases.h only

#pragma once

//
// Test function prototype
//
TESTPROCAPI DXTnTest(LPTESTCASEARGS pTestCaseArgs);
TESTPROCAPI DXTnMipMapTest(LPTESTCASEARGS pTestCaseArgs);


//
// Number of frames generated by each call to test function
//
#define D3DMQA_DXTNTEST_FRAMECOUNT 1
#define D3DMQA_DXTNMIPMAPTEST_FRAMECOUNT 1

//
// Test Ordinal Extents
//
#define D3DMQA_DXTNTEST_BASE 5000
#define D3DMQA_DXTNTEST_COUNT 20
#define D3DMQA_DXTNTEST_MAX  (D3DMQA_DXTNTEST_BASE + D3DMQA_DXTNTEST_COUNT - 1)

#define D3DMQA_DXT1TEST_OFFSET 0
#define D3DMQA_DXT1TEST_COUNT 4

#define D3DMQA_DXT2TEST_OFFSET 4
#define D3DMQA_DXT2TEST_COUNT 4

#define D3DMQA_DXT3TEST_OFFSET 8
#define D3DMQA_DXT3TEST_COUNT 4

#define D3DMQA_DXT4TEST_OFFSET 12
#define D3DMQA_DXT4TEST_COUNT 4

#define D3DMQA_DXT5TEST_OFFSET 16
#define D3DMQA_DXT5TEST_COUNT 4

#define D3DMQA_DXTNMIPMAPTEST_BASE 5200
#define D3DMQA_DXTNMIPMAPTEST_COUNT 195
#define D3DMQA_DXTNMIPMAPTEST_MAX (D3DMQA_DXTNMIPMAPTEST_BASE + D3DMQA_DXTNMIPMAPTEST_COUNT - 1)

