//
// Copyright (c) Microsoft Corporation.  All rights reserved.
//
//
// Use of this source code is subject to the terms of the Microsoft shared
// source or premium shared source license agreement under which you licensed
// this source code. If you did not accept the terms of the license agreement,
// you are not authorized to use this source code. For the terms of the license,
// please see the license agreement between you and Microsoft or, if applicable,
// see the SOURCE.RTF on your install media or the root of your tools installation.
// THE SOURCE CODE IS PROVIDED "AS IS", WITH NO WARRANTIES.
//
// To be included from ..\TestCases.h only

#pragma once

//
// Test function prototype
//
TESTPROCAPI TexStageTest(LPTESTCASEARGS pTestCaseArgs);

//
// Number of frames generated by each call to test function
//
#define D3DMQA_TEXSTAGETEST_FRAMECOUNT 1

//
// Test Ordinal Extents
//
#define D3DMQA_TEXSTAGETEST_COUNT                    736
#define D3DMQA_TEXSTAGETEST_BASE                    4000
#define D3DMQA_TEXSTAGETEST_MAX                     (D3DMQA_TEXSTAGETEST_BASE+D3DMQA_TEXSTAGETEST_COUNT-1)

#define D3DMQA_TEXSTAGEONEARGNOALPHATEST_COUNT        64                     
#define D3DMQA_TEXSTAGEONEARGNOALPHATEST_BASE       4000
#define D3DMQA_TEXSTAGEONEARGNOALPHATEST_MAX        (D3DMQA_TEXSTAGEONEARGNOALPHATEST_BASE+D3DMQA_TEXSTAGEONEARGNOALPHATEST_COUNT-1)

#define D3DMQA_TEXSTAGETWOARGNOALPHATEST_COUNT       208                   
#define D3DMQA_TEXSTAGETWOARGNOALPHATEST_BASE       4064
#define D3DMQA_TEXSTAGETWOARGNOALPHATEST_MAX        (D3DMQA_TEXSTAGETWOARGNOALPHATEST_BASE+D3DMQA_TEXSTAGETWOARGNOALPHATEST_COUNT-1)

#define D3DMQA_TEXSTAGETHREEARGNOALPHATEST_COUNT      96                      
#define D3DMQA_TEXSTAGETHREEARGNOALPHATEST_BASE     4272
#define D3DMQA_TEXSTAGETHREEARGNOALPHATEST_MAX      (D3DMQA_TEXSTAGETHREEARGNOALPHATEST_BASE+D3DMQA_TEXSTAGETHREEARGNOALPHATEST_COUNT-1)

#define D3DMQA_TEXSTAGEWITHALPHATEST_BASE           4368

#define D3DMQA_TEXSTAGEONEARGWITHALPHATEST_COUNT      64                     
#define D3DMQA_TEXSTAGEONEARGWITHALPHATEST_BASE     4368
#define D3DMQA_TEXSTAGEONEARGWITHALPHATEST_MAX      (D3DMQA_TEXSTAGEONEARGWITHALPHATEST_BASE+D3DMQA_TEXSTAGEONEARGWITHALPHATEST_COUNT-1)

#define D3DMQA_TEXSTAGETWOARGWITHALPHATEST_COUNT     208                   
#define D3DMQA_TEXSTAGETWOARGWITHALPHATEST_BASE     4432
#define D3DMQA_TEXSTAGETWOARGWITHALPHATEST_MAX      (D3DMQA_TEXSTAGETWOARGWITHALPHATEST_BASE+D3DMQA_TEXSTAGETWOARGWITHALPHATEST_COUNT-1)

#define D3DMQA_TEXSTAGETHREEARGWITHALPHATEST_COUNT    96                      
#define D3DMQA_TEXSTAGETHREEARGWITHALPHATEST_BASE   4640
#define D3DMQA_TEXSTAGETHREEARGWITHALPHATEST_MAX    (D3DMQA_TEXSTAGETHREEARGWITHALPHATEST_BASE+D3DMQA_TEXSTAGETHREEARGWITHALPHATEST_COUNT-1)

