//
// Copyright (c) Microsoft Corporation.  All rights reserved.
//
//
// This source code is licensed under Microsoft Shared Source License
// Version 1.0 for Windows CE.
// For a copy of the license visit http://go.microsoft.com/fwlink/?LinkId=3223.
//
#ifndef __SOAPSERIALGUIDS_H__
	#define __SOAPSERIALGUIDS_H__

	#define DISPID_SOAPSERIALIZER_INIT							1
	#define DISPID_SOAPSERIALIZER_STARTENVELOPE              	2
	#define DISPID_SOAPSERIALIZER_ENDENVELOPE					3
	#define DISPID_SOAPSERIALIZER_STARTHEADER					4
	#define DISPID_SOAPSERIALIZER_STARTHEADERELEMENT			5
	#define DISPID_SOAPSERIALIZER_ENDHEADERELEMENT				6
	#define DISPID_SOAPSERIALIZER_ENDHEADER						7
	#define DISPID_SOAPSERIALIZER_STARTBODY						8
	#define DISPID_SOAPSERIALIZER_ENDBODY						9
	#define DISPID_SOAPSERIALIZER_STARTELEMENT					10
	#define DISPID_SOAPSERIALIZER_ENDELEMENT					11
	#define DISPID_SOAPSERIALIZER_ATTRIBUTE						12
	#define DISPID_SOAPSERIALIZER_NAMESPACE						13
	#define DISPID_SOAPSERIALIZER_DEFAULTNAMESPACE				14
	#define DISPID_SOAPSERIALIZER_WRITESTRING					15
	#define DISPID_SOAPSERIALIZER_WRITEBUFFER					16
	#define DISPID_SOAPSERIALIZER_STARTFAULT					17
	#define DISPID_SOAPSERIALIZER_STARTFAULTDETAIL				18
	#define DISPID_SOAPSERIALIZER_ENDFAULTDETAIL				19
	#define DISPID_SOAPSERIALIZER_ENDFAULT						20
	#define DISPID_SOAPSERIALIZER_RESET							21
	#define DISPID_SOAPSERIALIZER_WRITEXML                  22	
	#define DISPID_SOAPSERIALIZER_GETPREFIX                 23


	#define UUID_ISOAPSERIAL			   	ADE424F3-0474-4231-AB31-4A254897700B

	#define UUID_SOAPSERIALIZERLIB_LIBRARY	ADE424F3-75BD-471D-9649-98B34568733B

	#define CLSID_SOAPSERIALIZER		    ADE424F3-AA10-471D-8A0A-687534555900

#endif //__SOAPSERIALGUIDS_H__

